import { c } from "node_modules/vite/dist/node/moduleRunnerTransport.d-CXw_Ws6P";
const onePieceTitles = [
  "Romance Dawn",
  "Buggy the Clown,Don't Get Fooled Again",
  "Don't Get Fooled Again",
  "The Black Cat Pirates",
  "For Whom the Bell Tolls",
  "The Oath",
  "The Crap-Geezer",
  "I Won't Die",
  "Tears",
  "OK, Let's Stand Up!",
  "The Meanest Man In the East",
  "The Legend Begins",
  "It's All Right!",
  "Instinct",
  "Straight Ahead!!!",
  "Carrying On His Will",
  "Hiriluk's Cherry Blossoms",
  "Ace Arrives",
  "Rebellion",
  "Showdown At Alubarna",
  "Utopia",
  "HOPE!!",
  "Vivi's Adventure",
  "People's Dreams",
  "The 100 Million Berry Man",
  "Adventure on Kami's Island",
  "Overture",
  "Wyper the Berserker",
  "Oratorio",
  "Capriccio",
  "We'll Be Here",
  "Love Song",
  "Davy Back Fight",
  "The City of Water, Water Seven",
  "Captain",
  "The Ninth Justice",
  "Tom",
  "Rocketman!!",
  "Scramble",
  "Gear",
  "Declaration of War",
  "Pirates vs. CP9",
  "Legend of a Hero",
  "Let's Go Back",
  "You Have My Sympathies",
  "Adventure on Ghost Island",
  "Cloudy, Partly Bony",
  "Adventures of Oars",
  "Nightmare Luffy",
  "Arriving Again",
  "The Eleven Supernovas",
  "Roger and Rayleigh",
  "Natural Born King",
  "Unstoppable",
  "A Ray of Hope",
  "Thank You",
  "The Paramount War",
  "The Name of This Era is 'Whitebeard'",
  "The Death of Portgas D. Ace",
  "My Brother",
  "Romance Dawn for the New World",
  "Adventure on Fish-Man Island",
  "Otohime and Tiger",
  "100,000 vs. 10",
  "To Nothing",
  "The Road Toward the Sun",
  "Cool Fight",
  "Pirate Alliance",
  "S.A.D.",
  "Enter Doflamingo",
  "Colosseum of Scoundrels",
  "Dressrosa’s Forgotten",
  "Operation Dressrosa S.O.P.",
  "Ever at Your Side",
  "Repaying the Debt",
  "Just Keep Going",
  "Smile",
  "Champion of Evil",
  "Lucy!!",
  "Opening Speech",
  "Let's Go See Master Nekomamushi",
  "A World Abuzz",
  "Emperor of the Sea, Charlotte Linlin",
  "Luffy vs. Sanji",
  "Liar",
  "Emperor Assassination Plan",
  "Not Sweet",
  "Lion",
  "Bad End Musical",
  "The Holy Land Mary Geoise",
  "Adventure in the Land of Samurai",
  "Introducing Komurasaki the Oiran",
  "The Star of Ebisu Town",
  "A Soldier's Dream",
  "Oden's Adventure",
  "I Am Oden, and I Was Born to Boil",
  "My Bible",
  "Vassals of Glory",
  "Straw Hat Luffy",
  "Color of the Supreme King",
  "The Stars Take the Stage",
  "The Pivotal Clash",
  "The Warrior of Liberation",
  "Shogun of Wano, Kozuki Momonosuke",
  "Luffy's Dream",
  "A Genius's Dream",
  "The Hero of Legend",
  "Better Off Dead in This World",
  "On Your Side",
  "The Upheaval of the Era",
  "Adventure in Elbaph",
];

const oshiNoKoTitles = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];

const myDressupDarling = ["", "", "", "", "", "", "", "", "", "", "", "", ""];

const demonSlayerTitles = [
  "Cruelty",
  "It Was You",
  "Believe in Yourself",
  "Robust Blade",
  "To Hell",
  "The Demon Slayer Corps Gathers",
  "Trading Blows at Close Quarters",
  "The Strength of the Hashira",
  "Operation: Entertainment District",
  "Human and Demon",
  "A Close Fight",
  "The Upper Ranks Gather",
  "Transitions",
  "The Mu of Muichiro",
  "Daybreak and First Light",
  "Indestructible",
  "Successors",
  "Assaulted by Memories",
  "Flapping Butterfly Wings",
  "The Path of Opening a Steadfast Heart",
  "Ancient Memories",
  "The Wheel of Fate",
  "Life Shining Across the Years",
];

const jojosBizarreTitles = [
  "Dio the Invader",
  "The Thirst for Blood!",
  "The Dark Knights",
  "To the Chamber of the Two-Headed Dragon",
  "The Final Ripple!",
  "JoJo vs. the Ultimate Life-Form",
  "The Red Stone of Aja",
  "The Final Trial!",
  "Rushing Towards the Cliff of Death",
  "The Crimson Bubble",
  "The Warrior Returning to the Wind",
  "The Birth of the Ultimate Being!!",
  "The Evil Spirit",
  "Silver Chariot",
  "The Emperor and the Hanged Man",
  "Terror in India",
  "City of Death",
  "The Arabian Nightmare",
  "The Three Wishes ",
  "Iggy the Fool and the Great God Geb",
  "The Deadly Sword",
  "The Shadow of Set",
  "D'Arby the Gambler",
  "The Claws of Horus",
  "D'Arby the Player",
  "Showdown ",
  "Dio's World",
  "Journey's End",
  "Enter Josuke Higashikata",
  "Okuyasu and Keicho Nijimura",
  " Koichi Hirose (Echoes)",
  " Yukako Yamagishi Falls in Love",
  "Let's Go Eat Some Italian Food",
  "Let's Go Play at the Mangaka's House",
  " Rohan Kishibe's Adventure",
  " 'Shigechi's Harvest",
  "Yoshikage Kira Wants to Live Quietly",
  "Sheer Heart Attack",
  "Father's Tears",
  "Janken Boy Is Coming!",
  "Highway Star",
  "The Cat Likes Yoshikage Kira",
  "Enigma Is a Mystery!",
  "My Dad Is Not My Dad",
  "Another One Bites the Dust",
  "The Invincible Crazy D",
  "Goodbye, Morioh Town - The Golden Heart",
  "Gang Star Is My Dream",
  "Find Polpo's Fortune!",
  "Operative Buccellati: First Orders From The Boss",
  "Second Orders From The Boss: 'Retrieve the Key!'",
  "The Express Train Heading Towards Florence",
  "The Grateful Dead",
  "Gold Experience Retaliates",
  "The Venice Landing Operation",
  "The 'G' in Guts",
  "No Flightcode! Unearth the Boss' Past",
  "My Name Is Doppio",
  "Like the Falling Sky",
  "Meet the Man in the Coliseum!",
  "They Called Him Diavolo",
  "The Requiem Plays Quietly",
  "Sleeping Slaves",
  "Prisoner FE40536: Jolyne Cujoh",
  "Visitor to the Green Dolphin Street Prison",
  "Prisoner of Love",
  "Go! Foo Fighters",
  "Savage Garden Strategy (Head for the Courtyard!)",
  "Flash Flood Warning",
  "Ultra Security Solitary",
  "Burn Dragon's Dream",
  "Birth of the Green",
  "Awaken",
  "Head Out! Time for Heaven",
  "Escape...",
  "Sky High!",
  "Time for Heaven - Three Days Until the New Moon",
  "Heavy Weather",
  "Coming to Cape Canaveral",
  "Made in Heaven",
  "September 25, 1890 San Diego Beach",
  "First Stage: 15,000 Meters",
  "Second Stage: Arizona Desert Crossing",
  "Gyro Zeppeli's Mission",
  "The President's Conspiracy",
  "Scary Monsters",
  "A Little Grave on the Wide, Wide Prairie",
  "To a Man's World",
  "A Stormy Night Is Coming",
  "Illinois Skyline, Michigan Lakeline",
  "Make the Golden Rectangle!",
  "Conditions for the Body, Conditions for Friendship",
  "Wrecking Ball",
  "The Victor's Rights",
  "A Dream of Gettysburg",
  "Dirty Deeds Done Dirt Cheap",
  "D4C",
  "Ticket to Ride",
  "You Can't Get Rich",
  "Love Train - The World Is One",
];

export const Products = [
  {
    id: 1,
    name: "Chainsaw Man: Dog & Chainsaw Vol.1",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrc: "Chainsaw Man/vol1.jpg",
    imageAlt: "Product 1",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
  },
  {
    id: 2,
    name: "Chainsaw Man: Chainsaw vs. Bat Vol.2",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrc: "Chainsaw Man/vol2.jpg",
    imageAlt: "Product 2",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
  },
  {
    id: 3,
    name: "Chainsaw Man: Kill Denji Vol.3",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrc: "Chainsaw Man/vol3.jpg",
    imageAlt: "Product 3",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
  },
  {
    id: 4,
    name: "Chainsaw Man: The Gun is Mightier Vol.4",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrc: "Chainsaw Man/vol4.jpg",
    imageAlt: "Product 4",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
  },
  {
    id: 5,
    name: "Chainsaw Man: Minor Vol.5",
    href: "#",
    pages: "200 pages",
    price: "$6.99",
    imageSrc: "Chainsaw Man/vol5.jpg",
    imageAlt: "Product 5",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
  },
  {
    id: 6,
    name: "Chainsaw Man: Boom Boom Boom Vol.6",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrc: "Chainsaw Man/vol6.jpg",
    imageAlt: "Product 6",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
  },
  {
    id: 7,
    name: "Chainsaw Man: In a Dream Vol.7",
    href: "#",
    pages: "200 pages",
    price: "$6.99",
    imageSrc: "Chainsaw Man/vol7.jpg",
    imageAlt: "Product 7",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
  },
  {
    id: 8,
    name: "Chainsaw Man: Super Mess Vol.8",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrc: "Chainsaw Man/vol8.jpg",
    imageAlt: "Product 8",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
  },
  {
    id: 9,
    name: "Chainsaw Man: Bath Vol.9",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrc: "Chainsaw Man/vol9.jpg",
    imageAlt: "Product 9",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
  },
  {
    id: 10,
    name: "Chainsaw Man: A Dog's Feeling Vol.10",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrc: "Chainsaw Man/1000.png",
    imageAlt: "Product 10",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
  },
  {
    id: 11,
    name: "Chainsaw Man: Go Get 'Em, Chainsaw Man Vol.11",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrc: "Chainsaw Man/vol11.jpg",
    imageAlt: "Product 11",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
  },
  {
    id: 12,
    name: "Chainsaw Man: Bird and War Vol.12",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrc: "Chainsaw Man/yorujpg.jpg",
    imageAlt: "Product 12",
    quantity: 192,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
  },
  {
    id: 13,
    name: "Chainsaw Man: Spoiler Vol.13",
    href: "#",
    pages: "184 pages",
    price: "$6.99",
    imageSrc: "Chainsaw Man/vol13.jpg",
    imageAlt: "Product 13",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
  },
  {
    id: 14,
    name: "Chainsaw Man: I Wanna See Penguins! Vol.14",
    href: "#",
    pages: "184 pages",
    price: "$6.99",
    imageSrc: "Chainsaw Man/vol14.jpg",
    imageAlt: "Product 14",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
  },
  {
    id: 15,
    name: "Chainsaw Man: Hors D'oeuvre Vol.15",
    href: "#",
    pages: "200 pages",
    price: "$6.99",
    imageSrc: "Chainsaw Man/vol15.jpg",
    imageAlt: "Product 15",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
  },
  {
    id: 16,
    name: "Chainsaw Man: Ordinary Happiness Vol.16",
    href: "#",
    pages: "184 pages",
    price: "$6.99",
    imageSrc: "Chainsaw Man/vol16.jpg",
    imageAlt: "Product 16",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
  },
  {
    id: 17,
    name: "Chainsaw Man: Guns, Nails, Katana Vol.17",
    href: "#",
    pages: "184 pages",
    price: "$6.99",
    imageSrc: "Chainsaw Man/vol17.jpg",
    imageAlt: "Product 17",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
  },
  {
    id: 18,
    name: "Chainsaw Man: All Pets Vol.18",
    href: "#",
    pages: "184 pages",
    price: "$6.99",
    imageSrc: "Chainsaw Man/vol18.jpg",
    imageAlt: "Product 18",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
  },
  {
    id: 19,
    name: "Chainsaw Man: Everyday Scenery Vol.19",
    href: "#",
    pages: "184 pages",
    price: "$6.99",
    imageSrc: "Chainsaw Man/vol19.jpg",
    imageAlt: "Product 19",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
  },
  {
    id: 20,
    name: "Chainsaw Man: Two Children Vol.20",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrc: "Chainsaw Man/asa.jpg",
    imageAlt: "Product 20",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
  },
  {
    id: 21,
    name: "Blinding Darkness Vol.0",
    href: "#",
    pages: "200 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol0.jpg",
    imageAlt: "Product 21",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.8,
    reviewCount: 49000,
  },
  {
    id: 22,
    name: "Ryomen Sukuna Vol.1",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol1.jpg",
    imageAlt: "Product 22",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 23,
    name: "Fearsome Womb Vol.2",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol2.jpg",
    imageAlt: "Product 23",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 24,
    name: "Young Fish and Reverse Punishment Vol.3",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol3.jpg",
    imageAlt: "Product 24",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 25,
    name: "I'm Gonna Kill You! Vol.4",
    href: "#",
    pages: "200 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol4.jpg",
    imageAlt: "Product 25",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 26,
    name: "Kyoto Sister School Goodwill Event Vol.5",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol5.jpg",
    imageAlt: "Product 26",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 27,
    name: "Black Flash Vol.6",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol6.jpg",
    imageAlt: "Product 27",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 28,
    name: "The Origin of Obedience Vol.7",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol7.jpg",
    imageAlt: "Product 28",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 29,
    name: "Hidden Inventory Vol.8",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol8.jpg",
    imageAlt: "Product 29",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 30,
    name: "Premature Death Vol.9",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol9.jpg",
    imageAlt: "Product 30",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 31,
    name: "Evening Festival Vol.10",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol10.jpg",
    imageAlt: "Product 31",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 32,
    name: "The Shibuya Incident Gate Open Vol.11",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol11.jpg",
    imageAlt: "Product 32",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 33,
    name: "The Shibuya Incident Summon Vol.12",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol12.jpg",
    imageAlt: "Product 33",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 34,
    name: " The Shibuya Incident Thunderclap Vol.13",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol13.jpg",
    imageAlt: "Product 34",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 35,
    name: "The Shibuya Incident Right and Wrong Vol.14",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol14.jpg",
    imageAlt: "Product 35",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 36,
    name: "The Shibuya Incident Transformation Vol.15",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol15.jpg",
    imageAlt: "Product 36",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 37,
    name: "The Shibuya Incident Gate Closed Vol.16",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol16.jpg",
    imageAlt: "Product 37",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 38,
    name: "Perfect Preparation Vol.17",
    href: "#",
    pages: "200 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol17.jpg",
    imageAlt: "Product 38",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 39,
    name: "Fever Vol.18",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol18.jpg",
    imageAlt: "Product 39",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 40,
    name: "Tokyo No. 1 Colony Angry Man Vol.19",
    href: "#",
    pages: "EN 200/JP 208 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol19.jpg",
    imageAlt: "Product 40",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 41,
    name: "Sendai Colony: The Height of the Feast Vol.20",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol20.jpg",
    imageAlt: "Product 41",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 42,
    name: "Tokyo No. 2 Colony Incredible Luck Vol.21",
    href: "#",
    pages: "216 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol21.jpg",
    imageAlt: "Product 42",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 43,
    name: "Sakurajima Colony Rebirth Vol.22",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol22.jpg",
    imageAlt: "Product 43",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 44,
    name: "Stars and Oil Vol.23",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol23.jpg",
    imageAlt: "Product 44",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 45,
    name: "Fearsome Womb Recurrence Vol.24",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol24.jpg",
    imageAlt: "Product 45",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 46,
    name: "Inhuman Makyo Shinjuku Showdown Vol.25",
    href: "#",
    pages: "208 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol25.jpg",
    imageAlt: "Product 46",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 47,
    name: "Heading South Vol.26",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol26.jpg",
    imageAlt: "Product 47",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 48,
    name: "Foolish Survivor!! Vol.27",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol27.jpg",
    imageAlt: "Product 48",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 49,
    name: "Inhuman Makyo Shinjuku Showdown Nine Principles Vol.28",
    href: "#",
    pages: "200 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol28.jpg",
    imageAlt: "Product 49",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 50,
    name: "Inhuman Makyo Shinjuku Showdown Living Dead Vol.29",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol29.jpg",
    imageAlt: "Product 50",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  {
    id: 51,
    name: "From Now On Vol.30",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: "Jujutsu Kaisen/jjkvol30.jpg",
    imageAlt: "Product 51",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
  },
  ...onePieceTitles.map((title, index) => ({
    id: 52 + index,
    name: `One Piece: ${title} Vol.${index + 1}`,
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: `One Piece/onepiecevol${index + 1}.jpg`,
    imageAlt: `One Piece Vol. ${index + 1}`,
    quantity: 1,
    category: "One Piece",
    rating: 4.7,
    reviewCount: 290000,
  })),

  ...oshiNoKoTitles.map((title, index) => ({
    id: 165 + index,
    name: `Oshi No Ko: ${title} Vol.${index + 1}`,
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: `Oshi No Ko/oshinoko${index + 1}.jpg`,
    imageAlt: `Oshi No Ko Vol. ${index + 1}`,
    quantity: 1,
    category: "Oshi No Ko",
    rating: 4.4,
    reviewCount: 12000,
  })),

  ...demonSlayerTitles.map((title, index) => ({
    id: 200 + index,
    name: `Demon Slayer: ${title} Vol.${index + 1}`,
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: `Demon Slayer/demon${index + 1}.jpg`,
    imageAlt: `Demon Slayer Vol. ${index + 1}`,
    quantity: 1,
    category: "Demon Slayer",
    rating: 4.8,
    reviewCount: 183000,
  })),

  ...jojosBizarreTitles.map((title, index) => ({
    id: 250 + index,
    name: `JoJo's Bizarre Adventure: ${title} Vol.${index + 1}`,
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: `JoJo/jojo${index + 1}.jpg`,
    imageAlt: `JoJo's Bizarre Adventure Vol. ${index + 1}`,
    quantity: 1,
    category: "JoJo's Bizarre Adventure",
    rating: 4.7,
    reviewCount: 42000,
  })),

  ...myDressupDarling.map((title, index) => ({
    id: 350 + index,
    name: `My Dressup Darling: ${title} Vol.${index + 1}`,
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrc: `My Dressup Darling/darling${index + 1}.jpg`,
    imageAlt: `My Dressup Darling Vol. ${index + 1}`,
    quantity: 1,
    category: "My Dressup Darling",
    rating: 4.9,
    reviewCount: 160053,
  })),
];
