import { c } from "node_modules/vite/dist/node/moduleRunnerTransport.d-CXw_Ws6P";
const onePieceTitles = [
  "Romance Dawn",
  "Buggy the Clown,Don't Get Fooled Again",
  "Don't Get Fooled Again",
  "The Black Cat Pirates",
  "For Whom the Bell Tolls",
  "The Oath",
  "The Crap-Geezer",
  "I Won't Die",
  "Tears",
  "OK, Let's Stand Up!",
  "The Meanest Man In the East",
  "The Legend Begins",
  "It's All Right!",
  "Instinct",
  "Straight Ahead!!!",
  "Carrying On His Will",
  "Hiriluk's Cherry Blossoms",
  "Ace Arrives",
  "Rebellion",
  "Showdown At Alubarna",
  "Utopia",
  "HOPE!!",
  "Vivi's Adventure",
  "People's Dreams",
  "The 100 Million Berry Man",
  "Adventure on Kami's Island",
  "Overture",
  "Wyper the Berserker",
  "Oratorio",
  "Capriccio",
  "We'll Be Here",
  "Love Song",
  "Davy Back Fight",
  "The City of Water, Water Seven",
  "Captain",
  "The Ninth Justice",
  "Tom",
  "Rocketman!!",
  "Scramble",
  "Gear",
  "Declaration of War",
  "Pirates vs. CP9",
  "Legend of a Hero",
  "Let's Go Back",
  "You Have My Sympathies",
  "Adventure on Ghost Island",
  "Cloudy, Partly Bony",
  "Adventures of Oars",
  "Nightmare Luffy",
  "Arriving Again",
  "The Eleven Supernovas",
  "Roger and Rayleigh",
  "Natural Born King",
  "Unstoppable",
  "A Ray of Hope",
  "Thank You",
  "The Paramount War",
  "The Name of This Era is 'Whitebeard'",
  "The Death of Portgas D. Ace",
  "My Brother",
  "Romance Dawn for the New World",
  "Adventure on Fish-Man Island",
  "Otohime and Tiger",
  "100,000 vs. 10",
  "To Nothing",
  "The Road Toward the Sun",
  "Cool Fight",
  "Pirate Alliance",
  "S.A.D.",
  "Enter Doflamingo",
  "Colosseum of Scoundrels",
  "Dressrosa’s Forgotten",
  "Operation Dressrosa S.O.P.",
  "Ever at Your Side",
  "Repaying the Debt",
  "Just Keep Going",
  "Smile",
  "Champion of Evil",
  "Lucy!!",
  "Opening Speech",
  "Let's Go See Master Nekomamushi",
  "A World Abuzz",
  "Emperor of the Sea, Charlotte Linlin",
  "Luffy vs. Sanji",
  "Liar",
  "Emperor Assassination Plan",
  "Not Sweet",
  "Lion",
  "Bad End Musical",
  "The Holy Land Mary Geoise",
  "Adventure in the Land of Samurai",
  "Introducing Komurasaki the Oiran",
  "The Star of Ebisu Town",
  "A Soldier's Dream",
  "Oden's Adventure",
  "I Am Oden, and I Was Born to Boil",
  "My Bible",
  "Vassals of Glory",
  "Straw Hat Luffy",
  "Color of the Supreme King",
  "The Stars Take the Stage",
  "The Pivotal Clash",
  "The Warrior of Liberation",
  "Shogun of Wano, Kozuki Momonosuke",
  "Luffy's Dream",
  "A Genius's Dream",
  "The Hero of Legend",
  "Better Off Dead in This World",
  "On Your Side",
  "The Upheaval of the Era",
  "Adventure in Elbaph",
];

const oshiNoKoTitles = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];

const oshiNoKoCoverCharacters = [
  ["Ai Hoshino"],
  ["Ruby Hoshino"],
  ["Aqua Hoshino"],
  ["Kana Arima"],
  ["Akane Kurokawa"],
  ["Yoriko Kichijouji", "Abiko Samejima"],
  ["Ai Hoshino", "Aqua Hoshino", "Ruby Hoshino"],
  ["Mem-Cho"],
  ["Minami Kotobuki"],
  ["Aqua Hoshino"],
  ["Kana Arima"],
  ["Frill Shiranui"],
  ["Miyako Saitou"],
  ["Ai Hoshino", "Ruby Hoshino"],
  ["Akane Kurokawa", "Kana Arima"],
  ["Ai Hoshino"],
];

const oshiNoKoChapters = [
  [
    "Chapter 1: Mother & Children",
    "Chapter 2: Big Brother & Little Sister",
    "Chapter 3: Babysitter",
    "Chapter 4: How to Smile",
    "Chapter 5: Director & Actress",
    "Chapter 6: Child Actors",
    "Chapter 7: If You Fear Falling, You'll Fall Harder",
    "Chapter 8: Ai Hoshino Part 1",
    "Chapter 9: Ai Hoshino Part 2",
    "Chapter 10: Introduction",
  ],
  [
    "Chapter 11: Audition",
    "Chapter 12: The Third Option",
    "Chapter 13: Procedures",
    "Chapter 14: Connection",
    "Chapter 15: The Manga Drama",
    "Chapter 16: Acting Skills",
    "Chapter 17: Staging",
    "Chapter 18: Modest Praise",
    "Chapter 19: The Entertainment Department",
    "Chapter 20: New Member",
  ],
  [
    "Chapter 21: The Dating Reality Show",
    "Chapter 22: Wannable Idols",
    "Chapter 23: A Mark",
    "Chapter 24: Ego Search",
    "Chapter 25: Up in Flames",
    "Chapter 26: Storm",
    "Chapter 27: Viral",
    "Chapter 28: Role Creation",
    "Chapter 29: Perfect Copy",
    "Chapter 30: The First",
  ],
  [
    "Chapter 31: Love for Real",
    "Chapter 32: Appropriate Age",
    "Chapter 33: Motivation",
    "Chapter 34: Center",
    "Chapter 35: Responsible",
    "Chapter 36: The Night Before",
    "Chapter 37: Pressure",
    "Chapter 38: Group Fan",
    "Chapter 39: A Job That's Kinda Fun",
    "Chapter 40: Sore Loser",
  ],
  [
    "Chapter 41: Introductions",
    "Chapter 42: Read-Through",
    "Chapter 43: The Losing Heroine",
    "Chapter 44: The Visit",
    "Chapter 45: The Telephone Game",
    "Chapter 46: Theater",
    "Chapter 47: Studio Visit",
    "Chapter 48: Crunch Time",
    "Chapter 49: Rewriting",
    "Chapter 50: Emotional Acting",
  ],
  [
    "Chapter 51: Observation",
    "Chapter 52: Boyfriend-Girlfriend",
    "Chapter 53: Pickup",
    "Chapter 54: Point of Contention",
    "Chapter 55: The Curtains Rises",
    "Chapter 56: First Clash",
    "Chapter 57: Lousy",
    "Chapter 58: Growth",
    "Chapter 59: Aspiration",
    "Chapter 60: Sun",
  ],
  [
    "Chapter 61: Reacting",
    "Chapter 62: Ad-Lib",
    "Chapter 63: Genius Actor",
    "Chapter 64: Trigger",
    "Chapter 65: Regret",
    "Chapter 66: Curtain",
    "Chapter 67: Drinking Party",
    "Chapter 68: Release",
    "Chapter 69: Room Tour",
    "Chapter 70: Fire",
  ],
  [
    "Chapter 71: Pedestrian Bridge",
    "Chapter 72: Freedom",
    "Chapter 73: Smart",
    "Chapter 74: Takachiho",
    "Chapter 75: Mother and Mother",
    "Chapter 76: Music Video",
    "Chapter 77: Reunion",
    "Chapter 78: Use",
    "Chapter 79: Duty",
    "Chapter 80: Wish",
  ],
  [
    "Chapter 81: Progress",
    "Chapter 82: B-Komachi Nights",
    "Chapter 83: Fixation",
    "Chapter 84: Pitching an Idea",
    "Chapter 85: Calculation",
    "Chapter 86: AD",
    "Chapter 87: Lies",
    "Chapter 88: Offer",
    "Chapter 89: Cosplay",
    "Chapter 90: Compliance",
  ],
  [
    "Chapter 91: Dig Deep",
    "Chapter 92: Ritual Purification",
    "Chapter 93: Leak",
    "Chapter 94: Breakthrough",
    "Chapter 95: Blindness",
    "Chapter 96: White Roses",
    "Chapter 97: Together",
    "Chapter 98: Going Astray",
    "Chapter 99: Drinking",
    "Chapter 100: Business",
  ],
  [
    "Chapter 101: Predicament",
    "Chapter 102: Idol and Love",
    "Chapter 103: Scandal",
    "Chapter 104: Countermeasure",
    "Chapter 105: Reporter",
    "Chapter 106: Breaking Off",
    "Chapter 107: Friends",
    "Chapter 108: Plans",
    "Chapter 109: Night",
    "Chapter 110: How It Began",
  ],
  [
    "Chapter 111: Mammon-Worship and Passion",
    "Chapter 112: Towards the Future",
    "Chapter 113: Commercial Work",
    "Chapter 114: Interpersonal Audition",
    "Chapter 115: Roles",
    "Chapter 116: Responsibility",
    "Chapter 117: Panda",
    "Chapter 118: Activation",
    "Chapter 119: Biological Mother",
    "Chapter 120: Lack Of Ability",
  ],
  [
    "Chapter 121: Sarina Tendouji",
    "Chapter 122: Doc",
    "Chapter 123: Bad Move",
    "Chapter 124: Reversal",
    "Chapter 125: Dazzled",
    "Chapter 126: Management",
    "Chapter 127: Scouting A Girl",
    "Chapter 128: Script Reading",
    "Chapter 129: Piece",
    "Chapter 130: Basic Tactic",
  ],
  [
    "Chapter 131: Atonement",
    "Chapter 132: Nino",
    "Chapter 133: Acting",
    "Chapter 134: Depths",
    "Chapter 135: By Her Side",
    "Chapter 136: Fight",
    "Chapter 137: Idol",
    "Chapter 138: Amends",
    "Chapter 139: Lookism",
    "Chapter 140: Is This Right?",
    "Chapter 141: Chain",
  ],
  [
    "Chapter 142: Responsibility",
    "Chapter 143: Blind Follower",
    "Chapter 144: Fan of the Originals",
    "Chapter 145: Children",
    "Chapter 146: Role",
    "Chapter 147: Wish",
    "Chapter 148: End of Summer",
    "Chapter 149: By the Sea",
    "Chapter 150: Knife",
    "Chapter 151: Catch Ball",
    "Chapter 152: Interview",
  ],
  [
    "Chapter 153: Fiction",
    "Chapter 154: 15-Year Lie",
    "Chapter 155: Happy End",
    "Chapter 156: MEMe",
    "Chapter 157: An Ordinary Day, A Wonderful Day",
    "Chapter 158: Jewel",
    "Chapter 159: Resonance",
    "Chapter 160: Eye",
    "Chapter 161: Future",
    "Chapter 162: Aqua Hoshino",
    "Chapter 163: You",
    "Chapter 164: Finale",
    "Chapter 165: And Then",
    "Chapter 166: Star",
    "Chapter 166.5",
  ],
];

const myDressupDarling = ["", "", "", "", "", "", "", "", "", "", "", "", ""];

const myDressupDarlingCoverCharacters = [["Marin Kitagawa"]];

const myDressupDarlingChapters = [
  [
    "Chapter 1",
    "Chapter 2",
    "Chapter 3",
    "Chapter 4",
    "Chapter 5",
    "Chapter 6",
    "Chapter 7",
  ],
  [
    "Chapter 8",
    "Chapter 9",
    "Chapter 10",
    "Chapter 11",
    "Chapter 12",
    "Chapter 13",
    "Chapter 14",
    "Chapter 15",
  ],
  [
    "Chapter 16",
    "Chapter 17",
    "Chapter 18",
    "Chapter 19",
    "Chapter 20",
    "Chapter 21",
    "Chapter 22",
    "Chapter 23",
  ],
  [
    "Chapter 24",
    "Chapter 25",
    "Chapter 26",
    "Chapter 27",
    "Chapter 28",
    "Chapter 29",
    "Chapter 30",
    "Chapter 31",
  ],
  [
    "Chapter 32",
    "Chapter 33",
    "Chapter 34",
    "Chapter 35",
    "Chapter 36",
    "Chapter 37",
    "Chapter 38",
    "Chapter 39",
  ],
  [
    "Chapter 40",
    "Chapter 41",
    "Chapter 42",
    "Chapter 43",
    "Chapter 44",
    "Chapter 45",
    "Chapter 46",
    "Chapter 47",
  ],
  [
    "Chapter 48",
    "Chapter 49",
    "Chapter 50",
    "Chapter 51",
    "Chapter 52",
    "Chapter 53",
    "Chapter 54",
    "Chapter 55",
  ],
  [
    "Chapter 56",
    "Chapter 57",
    "Chapter 58",
    "Chapter 59",
    "Chapter 60",
    "Chapter 61",
    "Chapter 62",
    "Chapter 63",
  ],
  [
    "Chapter 64",
    "Chapter 65",
    "Chapter 66",
    "Chapter 67",
    "Chapter 68",
    "Chapter 69",
    "Chapter 70",
    "Chapter 71",
  ],
  [
    "Chapter 72",
    "Chapter 73",
    "Chapter 74",
    "Chapter 75",
    "Chapter 76",
    "Chapter 77",
    "Chapter 78",
    "Chapter 79",
  ],
  [
    "Chapter 80",
    "Chapter 81",
    "Chapter 82",
    "Chapter 83",
    "Chapter 84",
    "Chapter 85",
    "Chapter 86",
    "Chapter 87",
  ],
  [
    "Chapter 88",
    "Chapter 89",
    "Chapter 90",
    "Extra Edition (番外編)",
    "Chapter 91",
    "Chapter 92",
    "Chapter 93",
    "Chapter 94",
    "Chapter 95",
  ],
  [
    "Chapter 96",
    "Chapter 97",
    "Chapter 98",
    "Chapter 99",
    "Chapter 100",
    "Chapter 101",
    "Chapter 102",
  ],
];

const demonSlayerTitles = [
  "Cruelty",
  "It Was You",
  "Believe in Yourself",
  "Robust Blade",
  "To Hell",
  "The Demon Slayer Corps Gathers",
  "Trading Blows at Close Quarters",
  "The Strength of the Hashira",
  "Operation: Entertainment District",
  "Human and Demon",
  "A Close Fight",
  "The Upper Ranks Gather",
  "Transitions",
  "The Mu of Muichiro",
  "Daybreak and First Light",
  "Indestructible",
  "Successors",
  "Assaulted by Memories",
  "Flapping Butterfly Wings",
  "The Path of Opening a Steadfast Heart",
  "Ancient Memories",
  "The Wheel of Fate",
  "Life Shining Across the Years",
];

const demonSlayerChapters = [
  [
    "1. Cruelty",
    "2. The Stranger",
    "3. Return by Dawn",
    "4. Tanjiro's Journal, Part 1",
    "5. Tanjiro's Journal, Part 2",
    "6. A Mountain of Hands",
    "7. Spirits of the Deceased",
  ],
  [
    "8. Big Brother",
    "9. Welcome Back",
    "10. Kidnapper's Bog",
    "11. Suggestion",
    "12. I Can't Tell You",
    "13. It Was You",
    "14. Kibutsuji's Wrath / The Smell of Enchanting Blood",
    "15. The Doctor's Opinion",
    "16. Playing Temari",
  ],
  [
    "17. Arrow Demon",
    "18. The Curse",
    "19. Together Forever",
    "20. Zenitsu Agatsuma",
    "21. Tsuzumi Mansion",
    "22. Rushing Boar",
    "23. The Boar Bares Its Fangs, Zenitsu Sleeps",
    "24. Former Member of the Twelve Kizuki",
    "25. Believe in Yourself",
  ],
  [
    "26. Barehanded Fight",
    "27. Inosuke Hashibira",
    "28. Urgent Summons",
    "29. Mount Natagumo",
    "30. Marionettes",
    "31. Letting Someone Else Go First",
    "32. Pungent Odor",
    "33. Suffering and Floundering as You Move Forward",
    "34. Robust Blade",
  ],
  [
    "35. Scattered",
    "36. This is Bad!",
    "37. Broken Blade",
    "38. Real and Fake",
    "39. Life Passing Before One's Eyes",
    "40. Hinokami",
    "41. Shinobu Kocho",
    "42. Behind",
    "43. To Hell",
  ],
  [
    "44. Against Corps Rules",
    "45. Trial by Hashira",
    "46. Master of the Mansion",
    "47. Hmph!",
    "48. Butterfly Mansion",
    "49. Rehabilitation Training, Part 1",
    "50. Rehabilitation Training, Part 2",
    "51. The Nichirin Sword Returns",
    "52. Cruel and Heartless",
  ],
  [
    "53. You Are",
    "54. Good Evening, Rengoku",
    "55. Train of Infinite Dreams",
    "56. Wake Up",
    "57. Draw Your Blade",
    "58. Good Morning",
    "59. Insult",
    "60. Defending 200 People",
    "61. Trading Blows at Close Quarters",
    "Bonus Manga",
  ],
  [
    "62. Ending in a Dream",
    "63. Akaza",
    "64. The Strength of the Hashira",
    "65. Whose Victory?",
    "66. Scattering into Dawn",
    "67. Looking for Something",
    "68. Wielder",
    "69. Move Forward—Even if Just a Little",
    "70. Kidnapper",
  ],
  [
    "71. Operation: Entertainment District",
    "72. Search For My Wives",
    "73. The Chase",
    "74. Daki",
    "75. Various Feelings",
    "76. In Various Places",
    "77. Roar",
    "78. Wriggly",
    "79. Air Hole",
  ],
  [
    "80. Value",
    "81. Layered Memories",
    "82. Human and Demon",
    "83. Transformation",
    "84. What is Important",
    "85. Weeping",
    "86. Gyutaro",
    "87. Gathering",
    "88. How to Defeat Them",
    "Bonus Chapter: Inosuke's Fairy Tale",
  ],
  [
    "89. A Close Fight",
    "90. Grateful",
    "91. A Change of Strategy",
    "92. Worm, Simpleton, Stupid Coward",
    "93. Never Give Up",
    "94. Do Something",
    "95. Final Moments",
    "96. No Matter How Many Lives, Part 1",
    "97. No Matter How Many Lives, Part 2",
  ],
  [
    "98. The Upper Ranks Gather",
    "99. Someone's Dream",
    "100. Go to the Village!!",
    "101. A Secret",
    "102. Hello, Tokito",
    "103. Yoriichi Type Zero",
    "104. Kotetsu",
    "105. Something Came Out",
    "106. Enemy Attack",
  ],
  [
    "107. In The Way",
    "108. Thank You, Tokito",
    "109. Won't Die",
    "110. Sneaking Around",
    "111. Pretentious Artist",
    "112. Transitions",
    "113. Bright Red Blade",
    "114. Wanted: Respect",
    "115. To Be a Hashira",
  ],
  [
    "116. Awful Villain",
    "117. Swordsmith",
    "118. The Mu of Muichiro",
    "119. Coming Back",
    "120. Trading Insults",
    "121. Abnormal Situation",
    "122. A Passing Moment of Excitement",
    "123. Mitsuri Kanroji's Life Passes Before Her Eyes",
    "124. Get it Together, Moron!",
  ],
  [
    "125. Dawn Approaches",
    "126. Daybreak and First Light",
    "127. The Rumble of Victory",
    "128. A Request for Instruction",
    "129. To Become a Marked One",
    "130. A Place to Be",
    "131. Visitor",
    "132. Full Strength Training",
    "133. Welcome",
  ],
  [
    "134. Repetitive Action",
    "135. Himejima Hell",
    "136. Moving",
    "137. Undying",
    "138. A Sudden Turn",
    "139. Falling",
    "140. The Final Battle Begins",
    "141. Vengeance",
    "142. Insect Hashira, Shinobu Kocho",
  ],
  [
    "143. Wrath",
    "144. Successors",
    "145. Box of Happiness",
    "146. Pride",
    "147. Small Cogs",
    "148. Clashing",
    "149. Disgust",
    "150. Noticing",
    "151. The Sound of Bells on a Snowy Moonlight Night",
  ],
  [
    "152. The Transparent World",
    "153. Pulled",
    "154. Assaulted by Memories",
    "155. Useless Komainu",
    "156. Thank You",
    "157. Returning Spirit",
    "158. Chaos",
    "159. Face",
    "160. Similar Features, Returning Memories",
  ],
  [
    "161. Flapping Butterfly Wings",
    "162. Trio of Victory",
    "163. Overflowing Heart",
    "164. Just Overdid It A Little",
    "165. Stunned and Trembling",
    "166. True Feelings",
    "167. A Request",
    "168. Never Disappear",
    "169. Rumbling",
  ],
  [
    "170. The Immovable Hashira",
    "171. Transformation",
    "172. A Weakling's Potential",
    "173. The Path of Opening a Steadfast Heart",
    "174. Nightmare on the Night of a Red Moon",
    "175. Respect for Future Generations",
    "176. Samurai",
    "177. Younger Brother",
    "178. Even If You Reach Out Your Hand",
  ],
  [
    "179. Feelings for Elder Brother, Feelings for Younger Brother",
    "180. Recovery",
    "181. Disaster",
    "182. Rage",
    "183. A Clash of Wills",
    "184. Leaving the Warfront",
    "185. A World Without Smell",
    "186. Ancient Memories",
    "187. Innocent Person",
  ],
  [
    "188. Sorrowful Love",
    "189. Reassuring Comrades",
    "190. One After Another",
    "191. Which One of Us is the Demon",
    "192. The Wheel of Fate",
    "193. A Difficult Door Begins to Open",
    "194. Burn Scars",
    "195. Bewilderment",
    "196. I Am",
  ],
  [
    "197. Tenacity",
    "198. The Next Thing We Knew...",
    "199. Millenial Dawn",
    "200. The Price of Victory",
    "201. The King of Demons",
    "202. Let's Go Home",
    "203. Voices of Encouragement",
    "204. A World Without Demons",
    "205. Life Shining Across the Years",
  ],
];

const demonSlayerCoverCharacters = [
  ["Tanjiro Kamado", "Nezuko Kamado"],
  ["Tanjiro Kamado", "Muzan Kibutsuji"],
  ["Tanjiro Kamado", "Zenitsu Agatsuma"],
  ["Tanjiro Kamado", "Inosuke Hashibira"],
  ["Giyu Tomioka"],
  ["Shinobu Kocho"],
  ["Inosuke Hashibira"],
  ["Kyojuro Rengoku"],
  ["Tengen Uzui"],
  ["Tanjiro Kamado"],
  ["Nezuko Kamado"],
  ["Muichiro Tokito"],
  ["Genya Shinazugawa"],
  ["Mitsuri Kanroji"],
  ["Gyomei Himejima"],
  ["Kagaya Ubuyashiki", "Amane Ubuyashiki"],
  ["Sanemi Shinazugawa"],
  ["Kanao Tsuyuri"],
  ["Obanai Iguro"],
  ["Yoriichi Tsugikuni"],
  ["Tamayo", "Yushiro"],
  ["Muzan Kibutsuji"],
  ["Tanjiro Kamado", "Nezuko Kamado"],
];

const jojosBizarreTitles = [
  "Dio the Invader",
  "The Thirst for Blood!",
  "The Dark Knights",
  "To the Chamber of the Two-Headed Dragon",
  "The Final Ripple!",
  "JoJo vs. the Ultimate Life-Form",
  "The Red Stone of Aja",
  "The Final Trial!",
  "Rushing Towards the Cliff of Death",
  "The Crimson Bubble",
  "The Warrior Returning to the Wind",
  "The Birth of the Ultimate Being!!",
  "The Evil Spirit",
  "Silver Chariot",
  "The Emperor and the Hanged Man",
  "Terror in India",
  "City of Death",
  "The Arabian Nightmare",
  "The Three Wishes ",
  "Iggy the Fool and the Great God Geb",
  "The Deadly Sword",
  "The Shadow of Set",
  "D'Arby the Gambler",
  "The Claws of Horus",
  "D'Arby the Player",
  "Showdown ",
  "Dio's World",
  "Journey's End",
  "Enter Josuke Higashikata",
  "Okuyasu and Keicho Nijimura",
  " Koichi Hirose (Echoes)",
  " Yukako Yamagishi Falls in Love",
  "Let's Go Eat Some Italian Food",
  "Let's Go Play at the Mangaka's House",
  " Rohan Kishibe's Adventure",
  " 'Shigechi's Harvest",
  "Yoshikage Kira Wants to Live Quietly",
  "Sheer Heart Attack",
  "Father's Tears",
  "Janken Boy Is Coming!",
  "Highway Star",
  "The Cat Likes Yoshikage Kira",
  "Enigma Is a Mystery!",
  "My Dad Is Not My Dad",
  "Another One Bites the Dust",
  "The Invincible Crazy D",
  "Goodbye, Morioh Town - The Golden Heart",
  "Gang Star Is My Dream",
  "Find Polpo's Fortune!",
  "Operative Buccellati: First Orders From The Boss",
  "Second Orders From The Boss: 'Retrieve the Key!'",
  "The Express Train Heading Towards Florence",
  "The Grateful Dead",
  "Gold Experience Retaliates",
  "The Venice Landing Operation",
  "The 'G' in Guts",
  "No Flightcode! Unearth the Boss' Past",
  "My Name Is Doppio",
  "Like the Falling Sky",
  "Meet the Man in the Coliseum!",
  "They Called Him Diavolo",
  "The Requiem Plays Quietly",
  "Sleeping Slaves",
  "Prisoner FE40536: Jolyne Cujoh",
  "Visitor to the Green Dolphin Street Prison",
  "Prisoner of Love",
  "Go! Foo Fighters",
  "Savage Garden Strategy (Head for the Courtyard!)",
  "Flash Flood Warning",
  "Ultra Security Solitary",
  "Burn Dragon's Dream",
  "Birth of the Green",
  "Awaken",
  "Head Out! Time for Heaven",
  "Escape...",
  "Sky High!",
  "Time for Heaven - Three Days Until the New Moon",
  "Heavy Weather",
  "Coming to Cape Canaveral",
  "Made in Heaven",
  "September 25, 1890 San Diego Beach",
  "First Stage: 15,000 Meters",
  "Second Stage: Arizona Desert Crossing",
  "Gyro Zeppeli's Mission",
  "The President's Conspiracy",
  "Scary Monsters",
  "A Little Grave on the Wide, Wide Prairie",
  "To a Man's World",
  "A Stormy Night Is Coming",
  "Illinois Skyline, Michigan Lakeline",
  "Make the Golden Rectangle!",
  "Conditions for the Body, Conditions for Friendship",
  "Wrecking Ball",
  "The Victor's Rights",
  "A Dream of Gettysburg",
  "Dirty Deeds Done Dirt Cheap",
  "D4C",
  "Ticket to Ride",
  "You Can't Get Rich",
  "Love Train - The World Is One",
];

export const Products = [
  {
    id: 1,
    name: "Chainsaw Man: Dog & Chainsaw Vol.1",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrcEnglish: `Chainsaw Man/cm1.jpg`,
    imageSrcJapanese: `Chainsaw Man/vol1.jpg`,
    imageAlt: "Product 1",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
    chaptersList: [
      "01. Dog & Chainsaw (犬いぬとチェンソー Inu to Chensō?)",
      "02. The Place Where Pochita Is (ポチタの行ゆく方え Pochita no Yukue?)",
      "03. Arrival in Tokyo (東とう京きょう到とう着ちゃく Tōkyō Tōchaku?)",
      "04. Power (力パワー Pawā?)",
      "05. A Way to Touch Some Boobs (胸むねを揉もむ方ほう法ほう Mune o Momu Hōhō?)",
      "06. Service (使し役えき Shieki?)",
      "07. Meowy's Whereabouts (ニャーコの行ゆく方え Nyāko no Yukue?)",
    ],
    coverCharacters: ["Denji"],
  },
  {
    id: 2,
    name: "Chainsaw Man: Chainsaw vs. Bat Vol.2",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrcEnglish: `Chainsaw Man/cm2.jpg`,
    imageSrcJapanese: `Chainsaw Man/vol2.jpg`,
    imageAlt: "Product 2",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
    chaptersList: [
      "08. Chainsaw vs. Bat (チェーンソーVSバーサスコウモリ Chēnsō Bāsasu Kōmori?)",
      "09. Rescue (救きゅう出しゅつ Kyūshutsu?)",
      "10. Kon (コン Kon?)",
      "11. Compromise (妥だ協きょう Dakyō?)",
      "12. Squeeze (揉もむ Momu?)",
      "13. Gun Devil (銃じゅうの悪あく魔ま Jū no Akuma?)",
      "14. French Kiss (エロキス Erokisu?)",
      "15. Endless 8th Floor (エンドレス8階かい Endoresu Hachi-kai?)",
      "16. The First Taste (はじめての味あじ Hajimete no Aji?)",
    ],
    coverCharacters: ["Power"],
  },
  {
    id: 3,
    name: "Chainsaw Man: Kill Denji Vol.3",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrcEnglish: `Chainsaw Man/cm3.jpg`,
    imageSrcJapanese: `Chainsaw Man/vol3.jpg`,
    imageAlt: "Product 3",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
    chaptersList: [
      "17. Kill Denji (デンジを殺ころせ Denji o Korose?)",
      "18. Chainsaw vs Eternity (チェンソーVSバーサス永遠えいえん Chensō Bāsasu Eien?)",
      "19. Nobel Prize (ノーベル賞しょう Nōberu-shō?)",
      "20. Drinking (飲のみ Nomi?)",
      "21. Taste of a Kiss (キスのお味あじ Kisu no Oaji?)",
      "22. Cola-Flavor Chupa Chups (チュッパチャップスコーラ味あじ Chuppa Chappusu Kōra Aji?)",
      "23. Gunfire (銃じゅう声せい Jūsei?)",
      "24. Curse (呪のろい Noroi?)",
      "25. Ghost, Snake, Chainsaw (ゴースト・ヘビ・チェンソー Gōsuto Hebi Chensō?)",
    ],
    coverCharacters: ["Himeno"],
  },
  {
    id: 4,
    name: "Chainsaw Man: The Gun is Mightier Vol.4",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrcEnglish: `Chainsaw Man/cm4.jpg`,
    imageSrcJapanese: `Chainsaw Man/vol4.jpg`,
    imageAlt: "Product 4",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
    chaptersList: [
      "26. The Gun is Mightier (銃じゅうは強つよし Jū wa tsuyoshi?)",
      "27. From Kyoto (京きょう都とより Kyōto yori?)",
      "28. Secrets & Lies (秘ひ密みつと嘘うそ Himitsu to Uso?)",
      "29. Perfect Score (100点てん満まん点てん Hyaku-ten Manten?)",
      "30. Bruised & Battered (もっとボロボロ Motto Boroboro?)",
      "31. The Future Rules (未み来らい最さい高こう Mirai Saikō?)",
      "32. Over and Over Again (繰くり返かえし繰くり返かえし Kurikaeshi Kurikaeshi?)",
      "33. Mission Start (作さく戦せん開かい始し Sakusen Kaishi?)",
      "34. Full Team (全ぜん員いん集しゅう合ごう Zen'in Shūgō?)",
    ],
    coverCharacters: ["Aki Hayakawa"],
  },
  {
    id: 5,
    name: "Chainsaw Man: Minor Vol.5",
    href: "#",
    pages: "200 pages",
    price: "$6.99",
    imageSrcEnglish: `Chainsaw Man/cm5.jpg`,
    imageSrcJapanese: `Chainsaw Man/vol5.jpg`,
    imageAlt: "Product 5",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
    chaptersList: [
      "35. Minor (未み成せい年ねん Miseinen?)",
      "36. Katana vs. Chainsaw (日に本ほん刀とうVSバーサスチェンソー Nihontō Bāsasu Chensō?)",
      "37. Train, Head, Chainsaw (電でん車しゃ・頭あたま・チェンソー Densha Atama Chensō?)",
      "38. Easy Revenge! (気き楽らくに復ふく讐しゅうを! Kiraku ni Fukushū o!?)",
      "39. Tearjerker (きっと泣なく Kitto Naku?)",
      "40. Love, Flower, Chainsaw (恋こい・花はな・チェンソー Koi, Hana, Chensō?)",
      "41. Before the Storm (嵐あらしの前まえ Arashi no Mae?)",
      "42. Teach Me How To Swim (泳およぎ方かたを教おしえて Oyogikata o oshiete?)",
      "43. Jane Fell Asleep in the Church (ジェーンは教きょう会かいで眠ねむった Jēn wa Kyōkai de Nemutta?)",
    ],
    coverCharacters: ["Denji", "Katana Man"],
  },
  {
    id: 6,
    name: "Chainsaw Man: Boom Boom Boom Vol.6",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrcEnglish: `Chainsaw Man/cm6.jpg`,
    imageSrcJapanese: `Chainsaw Man/vol6.jpg`,
    imageAlt: "Product 6",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
    chaptersList: [
      "44. Boom Boom Boom (バン バン バン Ban ban ban?)",
      "45. A Fine Day for Explosions (爆ばく発はつ日び和より Bakuhatsu Biyori?)",
      "46. Massacre Melody (皆殺みなごろしのメロディ Minagoroshi no Merodi?)",
      "47. Luck with Women (女おんな運うん On'na Un?)",
      "48. Kaboom Kaboom Kaboom (ボンボンボン Bon Bon Bon?)",
      "49. Shark Hurricane (サメハリケーン Same Harikēn?)",
      "50. Sharknado (シャークネード Shākunēdo?)",
      "51. Dark Diving (ダークダイビング Dāku Daibingu?)",
      "52. Lost Love, Flower, Chainsaw (失恋しつれん・花はな・チェンソー Shitsuren・Hana・Chensō?)",
    ],
    coverCharacters: ["Denji", "Reze"],
  },
  {
    id: 7,
    name: "Chainsaw Man: In a Dream Vol.7",
    href: "#",
    pages: "200 pages",
    price: "$6.99",
    imageSrcEnglish: `Chainsaw Man/cm7.jpg`,
    imageSrcJapanese: `Chainsaw Man/vol7.jpg`,
    imageAlt: "Product 7",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
    chaptersList: [
      "53. In a Dream (夢ゆめの中なか Yume no Naka?)",
      "54. To Go to Enoshima (江えの島しまにいくには Enoshima ni Ikuni wa?)",
      "55. Let's Go (レッツゴー Rettsu Gō?)",
      "56. A Curse and A First (呪のろいと初はじめて Noroi to Hajimete?)",
      "57. Suddenly (突とつ然ぜん Totsuzen?)",
      "58. Yutaro Kurose (黒くろ瀬せ ユウタロウ Kurose Yūtarō?)",
      "59. Mess (めちゃくちゃ Mechakucha?)",
      "60. Quanxi and Fiends' 49-Person Massacre (クァンシと魔ま人じん達たち四よん十じゅう九きゅう人にん斬ぎり Kwanshi to Majin-tachi Yonjūkyūnin-Giri?)",
      "61. News Reporter (ニュースレポーター Nyūsu Repōtā?)",
    ],
    coverCharacters: [
      "Denji",
      "Master",
      "Eldest Brother",
      "Quanxi",
      "Santa Claus",
    ],
  },
  {
    id: 8,
    name: "Chainsaw Man: Super Mess Vol.8",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrcEnglish: `Chainsaw Man/cm8.jpg`,
    imageSrcJapanese: `Chainsaw Man/vol8.jpg`,
    imageAlt: "Product 8",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
    chaptersList: [
      "62. Super Mess (ちょうめちゃくちゃ Chō Mechakucha?)",
      "63. Trip to Hell (地じ獄ごく旅りょ行こう Jigoku Ryokō?)",
      "64. Welcome to Hell (ウェルカムトゥーデヘル Werukamu tū de Heru?)",
      "65. The Darkness Devil (闇やみの悪あく魔ま Yami no Akuma?)",
      "66. Woof! (ワン！ Wan!?)",
      "67. The First Devil Hunter (最サイ初ショのデビルハンター Saisho no Debiru Hantā?)",
      "68. Dark Power (ダークパワー Dāku Pawā?)",
      "69. Shining Power (シャイニングパワー Shainingu Pawā?)",
      "70. Pinch (摘つむ Tsumu?)",
    ],
    coverCharacters: ["Denji", "Quanxi"],
  },
  {
    id: 9,
    name: "Chainsaw Man: Bath Vol.9",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrcEnglish: `Chainsaw Man/cm9.jpg`,
    imageSrcJapanese: `Chainsaw Man/vol9.jpg`,
    imageAlt: "Product 9",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
    chaptersList: [
      "71. Bath (お風ふ呂ろ Ofuro?)",
      "72. All Together (みんな一いっ緒しょ Min'na Issho?)",
      "73. Everyday Life No More (日にち常じょうの終おわりに Nichijō no Owari ni?)",
      "74. What the Waves Say (波なみの言いう事こと Nami no Iukoto?)",
      "75. 9, 12 (9,12 Kyū, Jūni?)",
      "76. Don't Open It (開あけちゃダメ Akecha Dame?)",
      "77. Ring Ring Ring (チャイムチャイムチャイム Chaimu Chaimu Chaimu?)",
      "78. Snowball Fight (ゆきがっせん Yuki Gassen?)",
      "79. Play Catch (キャッチボール Kyatchi Bōru?)",
    ],
    coverCharacters: ["Aki Hayakawa", "Angel Devil"],
  },
  {
    id: 10,
    name: "Chainsaw Man: A Dog's Feeling Vol.10",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrcEnglish: `Chainsaw Man/cm10.jpg`,
    imageSrcJapanese: `Chainsaw Man/1000.png`,
    imageAlt: "Product 10",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
    chaptersList: [
      "80. A Dog's Feeling (犬いぬの気き持もち Inu no Kimochi?)",
      "81. Paw (おてて Otete?)",
      "82. Always Eat a Hearty Breakfast (朝ちょう食そくはしっかり Chōshoku wa Shikkari?)",
      "83. Death, Resurrection, Chainsaw (死し・復活ふっかつ・チェンソー Shi Fukkatsu Chensō?)",
      "84. Hero of Hell (地じ獄ごくのヒーロー Jigoku no Hīrō?)",
      "85. Bloody Good Gut Feeling (超ちょう跳ちょう腸ちょう・胃い胃い肝かん血ぢ Chō Chō Chō - Ī Kanji?)",
      "86. Date Chainsaw (デートチェンソー Dēto Chensō?)",
      "87. Chainsaw Man Vs. the Horrifying Weapon Humans (チェンソーマンVSバーサス恐きょう怖ふの武器ぶき人間にんげん Chensō Man Bāsasu Kyōfu no Buki Ningen?)",
      "88. Star Chainsaw (スターチェンソー Sutā Chensō?)",
    ],
    coverCharacters: ["Makima"],
  },
  {
    id: 11,
    name: "Chainsaw Man: Go Get 'Em, Chainsaw Man Vol.11",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrcEnglish: `Chainsaw Man/cm11.jpg`,
    imageSrcJapanese: `Chainsaw Man/vol11.jpg`,
    imageAlt: "Product 11",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
    chaptersList: [
      "89. Go Get 'Em, Chainsaw Man (がんばれチェンソーマン Ganbare Chensōman?)",
      "90. Super Power (超ちょうパワー Chō Pawā?)",
      "91. Power, Power, Power (パワー・パワー・パワー Pawā Pawā Pawā?)",
      "92. Vanilla Sky (バニラスカイ Banira Sukai?)",
      "93. You & Crappy Movies (君きみと糞くそ映えい画が Kimi to Kuso Eiga?)",
      "94. Chainsaw Man vs. the Weapon Humans (チェンソーマン対たい武器ぶき人間にんげんズ Chensōman-tai Buki Ningenzu?)",
      "95. Chainsaw Man vs. Control Devil (チェンソーマンVSバーサス支し配はいの悪あく魔ま Chensōman Bāsasu Shihai no Akuma?)",
      "96. This Kind of Taste (こんな味あじ Kon'na Aji?)",
      "97. I, Love, Chainsaw (愛あい・ラブ・チェンソー Ai Rabu Chensō?)",
    ],
    coverCharacters: ["Denji"],
  },
  {
    id: 12,
    name: "Chainsaw Man: Bird and War Vol.12",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrcEnglish: `Chainsaw Man/cm12.jpg`,
    imageSrcJapanese: `Chainsaw Man/yorujpg.jpg`,
    imageAlt: "Product 12",
    quantity: 192,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
    chaptersList: [
      "98. Bird and War (鳥とりと戦せん争そう Tori to Sensō?)",
      "99. Two Birds (２羽わ Ni wa?)",
      "100. How to Walk Shoeless (裸足はだしの歩あるき方かた Hadashi no Arukikata?)",
      "101. After School Devil Hunters (放ほう課か後ごデビルハンター Hōkago Debiru Hantā?)",
      "102. Save the Cat (セーブザキャット Sēbu za Kyatto?)",
      "103. Denji Dream (デンジドリーム Denji Dorīmu?)",
    ],
    coverCharacters: ["Yoru"],
  },
  {
    id: 13,
    name: "Chainsaw Man: Spoiler Vol.13",
    href: "#",
    pages: "184 pages",
    price: "$6.99",
    imageSrcEnglish: `Chainsaw Man/cm13.jpg`,
    imageSrcJapanese: `Chainsaw Man/vol13.jpg`,
    imageAlt: "Product 13",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
    chaptersList: [
      "104. Spoiler (ネタバレ Netabare?)",
      "105. Red Hot (灼しゃく熱ねつ Shakunetsu?)",
      "106. Bonfire (焚たき火び Takibi?)",
      "107. School Attacker (学がっ校こうの襲しゅう撃げき者しゃ Gakkō no Shūgeki-sha?)",
      "108. Something Important to Asa (アサの大たい切せつなもの Asa no Taisetsu na mono?)",
      "109. The Easy Way to Stop Bullying (簡単かんたんなイジメのなくしかれ Kantan na Ijime no Nakushikare?)",
      "110. A Ring in the Night (夜よるのチャイム Yoru no Chaimu?)",
      "111. Aha Ha Ha Ha (Ahahahaha アハハハハ?)",
      "112. Between Cat and Criminal (猫ねこと犯はん罪ざい者しゃの間あいだ Neko to Hanzai-sha no Aida?)",
    ],
    coverCharacters: ["Yuko"],
  },
  {
    id: 14,
    name: "Chainsaw Man: I Wanna See Penguins! Vol.14",
    href: "#",
    pages: "184 pages",
    price: "$6.99",
    imageSrcEnglish: `Chainsaw Man/cm14.jpg`,
    imageSrcJapanese: `Chainsaw Man/vol14.jpg`,
    imageAlt: "Product 14",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
    chaptersList: [
      "113. I Wanna See Penguins! (ペンギンが見みたい！ Pengin ga Mitai!?)",
      "114. Endless Aquarium (エンドレス水族館すいぞくかん Endoresu Suizokukan?)",
      "115. High Schoolers These Days (今時の高校生 Imadoki no kōkōsei?)",
      "116. Taste of Starfish (ヒトデの味あじ Hitode no Aji?)",
      "117. Penguin and Weapon (ペンギンと武ぶ器き Pengin to Buki?)",
      "118. Saying Goodbye (別わかれの挨あい拶さつ Wakare no Aisatsu?)",
      "119. Thief (泥どろ棒ぼう Dorobō?)",
      "120. Triangle (トライアングル Toraianguru?)",
      "121. Theory of Happiness (幸こう福ふく論ろん Kōfuku-ron?)",
      "122. The Prophecies (大だい予よ言げん Dai Yogen?)",
    ],
    coverCharacters: ["Fami"],
  },
  {
    id: 15,
    name: "Chainsaw Man: Hors D'oeuvre Vol.15",
    href: "#",
    pages: "200 pages",
    price: "$6.99",
    imageSrcEnglish: `Chainsaw Man/cm15.jpg`,
    imageSrcJapanese: `Chainsaw Man/vol15.jpg`,
    imageAlt: "Product 15",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
    chaptersList: [
      "123. Hors D'oeuvre (前ぜん菜さい Zensai?)",
      "124. Soup (スープ Sūpu?)",
      "125. Apple Thief (林りん檎ご万まん引びき犯はん Ringo Manbiki-han?)",
      "126. Food Fight (ぐちゃぐちゃファイト Guchagucha Faito?)",
      "127. Save the Asa (セーブザアサ Sēbu za Asa?)",
      "128. Main Dish (メインディッシュ Mein Disshu?)",
      "129. Save Me, Chainsaw Man (助たすけてチェンソーマン Tasukete Chensōman?)",
      "130. Kill Building (斬きるビル Kiru Biru?)",
      "131. Taste of Crap (糞クソの味あじ Kuso no Aji?)",
      "132. Protection (保ほ護ご Hogo?)",
      "133. Chainsaw Man Protest (チェンソーマンデモ Chensōman Demo?)",
    ],
    coverCharacters: ["Falling Devil"],
  },
  {
    id: 16,
    name: "Chainsaw Man: Ordinary Happiness Vol.16",
    href: "#",
    pages: "184 pages",
    price: "$6.99",
    imageSrcEnglish: `Chainsaw Man/cm16.jpg`,
    imageSrcJapanese: `Chainsaw Man/vol16.jpg`,
    imageAlt: "Product 16",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
    chaptersList: [
      "134. Ordinary Happiness (普ふ通つうの幸しあわせ Futsū no Shiawase?)",
      "135. Sentimental Drive (センチメンタルドライブ Senchimentaru Doraibu?)",
      "136. Normal Life (普ふ通つうの日ひ々び Futsū no Hibi?)",
      "137. Chu Chu Lovely Muni Muni Mura Mura (チューチューラブリームニムニムラムラ Chū chū raburī muni muni mura mura?)",
      "138. Sword Man (ソードマン Sōdoman?)",
      "139. A Chair's Feelings (イスの気持きもち Isu no Kimochi?)",
      "140. Scales (天秤てんびん Tenbin?)",
      "141. Normal Life Plus (普ふ通つうの人じん生せいプルス Futsū no Jinsei Purusu?)",
      "142. Denji Fan Club (デンジファンクラブ Denji Fan Kurabu?)",
      "143. Rawr (がおー Gaō?)",
    ],
    coverCharacters: ["Miri Sugo"],
  },
  {
    id: 17,
    name: "Chainsaw Man: Guns, Nails, Katana Vol.17",
    href: "#",
    pages: "184 pages",
    price: "$6.99",
    imageSrcEnglish: `Chainsaw Man/cm17.jpg`,
    imageSrcJapanese: `Chainsaw Man/vol17.jpg`,
    imageAlt: "Product 17",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
    chaptersList: [
      "144. Guns, Nails, Katana (銃じゅう・釘くぎ・刀かたな Jū, Kugi, Katana?)",
      "145. Kumbaya (クンバヤ Kunbaya?)",
      "146. Chainsaw Man War (チェンソーマン戦せん争そう Chensōman Sensō?)",
      "147. Cremation (火か葬そう Kasō?)",
      "148. Room 606 Sword (606号ごう室しつ剣けん 606-Gōshitsu ken?)",
      "149. Devil's Choice (悪あく魔まの選せん択たく Akuma no Sentaku?)",
      "150. Dream's Next Stage (夢ゆめの次つぎ Yume no Tsugi?)",
      "151. The Return of Chainsaw Man (帰かえってきたチェンソーマン Kaettekita Chensōman?)",
      "152. Massage (マッサージ Massāji?)",
      "153. Chainsaw Man Hunters (チェンソーマンハンター Chensōman Hantā?)",
    ],
    coverCharacters: ["Hirofumi Yoshida"],
  },
  {
    id: 18,
    name: "Chainsaw Man: All Pets Vol.18",
    href: "#",
    pages: "184 pages",
    price: "$6.99",
    imageSrcEnglish: `Chainsaw Man/cm18.jpg`,
    imageSrcJapanese: `Chainsaw Man/vol18.jpg`,
    imageAlt: "Product 18",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
    chaptersList: [
      "154. All Pets (みんなペット Minna Petto?)",
      "155. The Old Me (前まえの私わたし Mae no Watashi?)",
      "156. Whup Whup Whup Whup Bzzz Split Split (ババババヴヴヴヴバラバラ Babababa vuvuvuvu barabara?)",
      "157. College Fund (進しん学がく資し金きん Shingaku Shikin?)",
      "158. Gyohnee Guillotine (ギョニーギロチン Gyonī Girochin?)",
      "159. Attack on Samurai (アタックオンサムライ Atakku on Samurai?)",
      "160. That For Which The Heart Beats (心しん臓ぞうの動うごく向むき Shinzō no Ugoku Muki?)",
      "161. Chainsaw Man Puzzle (チェンソーマンパズル Chensōman Pazuru?)",
      "162. Fearsome (恐おそろしい奴やつ Osoroshī Yatsu?)",
      "163. Dream Balls (夢ゆめのタマキン Yume no Tamakin?)",
      "164. Charred Remains (焼やけ跡あと Yakeato?)",
    ],
    coverCharacters: ["Nayuta"],
  },
  {
    id: 19,
    name: "Chainsaw Man: Everyday Scenery Vol.19",
    href: "#",
    pages: "184 pages",
    price: "$6.99",
    imageSrcEnglish: `Chainsaw Man/cm19.jpg`,
    imageSrcJapanese: `Chainsaw Man/vol19.jpg`,
    imageAlt: "Product 19",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
    chaptersList: [
      "165. Everyday Scenery (いつもの風ふう景けい Itsumo no Fūkei?)",
      "166. Rain, Brothel, Removal (雨あめ・ソープ・切断せつだん Ame, Sōpu, Setsudan?)",
      "167. Super Smooch (超ちょうチュー Chō Chū?)",
      "168. Kiss, Love, Sperm (キス・好すき・スペルマ Kisu, Suki, Superuma?)",
      "169. Hands and Adaptation (手てと適てき応おう Te to Tekiō?)",
      "170. How to Eat Sushi (寿司すしの食たべ方かた Sushi no Tabekata?)",
      "171. Special Division 5 (特とく異い5課か Tokui 5-ka?)",
      "172. Bzzz! Boom! Chomp! (ヴヴン！ドオン！ガブ！ Vuvun! Doon! Gabu!?)",
      "173. Hard of Hearing (少すこし聞きこえてる Sukoshi Kikoe Teru?)",
      "174. Ayyy, Aging (おーい老おい Ōi oi?)",
      "175. Both Hands (両りょうの手て Ryō no Te?)",
    ],
    coverCharacters: ["Fumiko Mifune"],
  },
  {
    id: 20,
    name: "Chainsaw Man: Two Children Vol.20",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrcEnglish: `Chainsaw Man/cm20.jpg`,
    imageSrcJapanese: `Chainsaw Man/asa.jpg`,
    imageAlt: "Product 20",
    quantity: 1,
    category: "Chainsaw Man",
    rating: 4.7,
    reviewCount: 73000,
    chaptersList: [
      "176. Two Children (二に子し Nishi?)",
      "177. Trigger Finger (人ひと差さし指ゆび Hitosashi Yubi?)",
      "178. Gun Goddess (銃じゅうの女め神がみ Jū no Megami?)",
      "179. Vamvagah (ヴァンヴァガ Van'vaga?)",
      "180. Aging’s World (老おいの世せ界かい Oi no Sekai?)",
      "181. Trees on the Mind (気きになる木き Ki ni naru Ki?)",
      "182. Cute (可か愛わいい顔かお Kawaii Kao?)",
      "183. Barf, Head, Perv (ゲロ・顔かお・エロ Gero, Kao, Ero?)",
      "184. Run, Denji! (走はしれデンジ Hashire Denji?)",
      "185. Stomach in Another World (胃は異世界 I wa Isekai?)",
      "186. Yank, Blorsh, Bdroom (ギュッ・ボッ・ヴヴン Gyu Bo Vuvun?)",
    ],
    coverCharacters: ["Asa Mitaka"],
  },
  {
    id: 21,
    name: "Blinding Darkness Vol.0",
    href: "#",
    pages: "200 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken0.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol0.jpg",
    imageAlt: "Product 21",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.8,
    reviewCount: 49000,
    chaptersList: [
      "000-1. The Cursed Child (呪のろいの子こ Noroi no Ko)",
      "000-2. Blacker and Blacker (黒くろく黒くろく Kuroku Kuroku)",
      "000-3. Punishment for the Weak (弱じゃく者じゃに罰ばつを Jakusha ni Batsu o)",
      "000-4. Bright Darkness (眩まぶしい闇やみ Mabushii Yami)",
    ],
    coverCharacters: ["Yuta Okkotsu", "Rika Orimoto"],
  },
  {
    id: 22,
    name: "Ryomen Sukuna Vol.1",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken1.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol1.jpg",
    imageAlt: "Product 22",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "001.Ryomen Sukuna (両りょう面めん宿すく儺な Ryōmen Sukuna)",
      "002.Secret Execution (秘ひ匿とく死し刑けい Hitoku Shikei)",
      "003.For Myself (自じ分ぶんのために Jibun no Tameni)",
      "004.Girl of Steel (鉄てっ骨こつ娘むすめ Tekkotsu Musume)",
      "005.Start (始はじまり Hajimari)",
      "006.Fearsome Womb (呪じゅ胎たい戴たい天てん Jutaitaiten)",
      "007.Fearsome Womb, Part 2 (呪じゅ胎たい戴たい天てんー弐にー Jutaitaiten -ni-)",
    ],
    coverCharacters: ["Yuji Itadori", "Sukuna"],
  },
  {
    id: 23,
    name: "Fearsome Womb Vol.2",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken2.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol2.jpg",
    imageAlt: "Product 23",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "008. Fearsome Womb, Part 3 (呪じゅ胎たい戴たい天てんー参さんー Jutaitaiten -san-?)",
      "009. Fearsome Womb, Part 4 (呪じゅ胎たい戴たい天てんー肆しー Jutaitaiten -shi-?)",
      "010. After the Rain (雨う後ご Ugo?)",
      "011. A Dream (ある夢む想そう Aru Musō?)",
      "012. Pushing Forward (邁まい進しん Maishin?)",
      "013. Watching Movies (映えい画が鑑かん賞しょう Eiga Kanshō?)",
      "014. Assault (急きゅう襲しゅう Kyūshū?)",
      "015. Domain (展てん開かい Tenkai?)",
      "016. Affection (情じょう Jō?)",
    ],
    coverCharacters: ["Megumi Fushiguro", "Nue"],
  },
  {
    id: 24,
    name: "Young Fish and Reverse Punishment Vol.3",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken3.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol3.jpg",
    imageAlt: "Product 24",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "017. Boring (退たい屈くつ Taikutsu?)",
      "018. Bottom (底てい辺へん Teihen?)",
      "019. Young Fish and Reverse Punishment (幼よう魚ぎょと逆さか罰ばち Yōgyo to Sakabachi?)",
      "020. Young Fish and Reverse Punishment, Part 2 (幼よう魚ぎょと逆さか罰ばちー弐にー Yōgyo to Sakabachi -ni-?)",
      "021. Young Fish and Reverse Punishment, Part 3 (幼よう魚ぎょと逆さか罰ばちー参さんー Yōgyo to Sakabachi -san-?)",
      "022. Young Fish and Reverse Punishment, Part 4 (幼よう魚ぎょと逆さか罰ばちー肆しー Yōgyo to Sakabachi -shi-?)",
      "023. Young Fish and Reverse Punishment, Part 5 (幼よう魚ぎょと逆さか罰ばちー伍ごー Yōgyo to Sakabachi -go-?)",
      "024. Young Fish and Reverse Punishment, Part 6 (幼よう魚ぎょと逆さか罰ばちー陸ろくー Yōgyo to Sakabachi -roku-?)",
      "025. Narrow-Minded (固こ陋ろう蠢しゅん愚ぐ Korōshungu?)",
    ],
    coverCharacters: ["Nobara Kugisaki"],
  },
  {
    id: 25,
    name: "I'm Gonna Kill You! Vol.4",
    href: "#",
    pages: "200 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken4.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol4.jpg",
    imageAlt: "Product 25",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "026. To You Someday (いつかの君きみへ Itsuka no Kimi e?)",
      "027. What If (もしも Moshimo?)",
      "028. I'm Gonna Kill You! (殺ころしてやる Koro Shite Yaru?)",
      "029. Growth (成せい長ちょう Seichō?)",
      "030. Selfishness (我わが儘まま Wagamama?)",
      "031. Tomorrow (また明日あした Mata Ashita?)",
      "032. Introspection (反はん省せい Hansei?)",
      "033. Kyoto Sister School Goodwill Event - Team Battle, Part 0 (京きょう都と姉し妹まい校こう交こう流りゅう会かいー団だん体たい戦せん⓪ー Kyōto Shimai-kō Kōryū-kai - Dantai-sen ⓪-?)",
      "034. Kyoto Sister School Goodwill Event - Team Battle, Part 1 (京きょう都と姉し妹まい校こう交こう流りゅう会かいー団だん体たい戦せん①ー Kyōto Shimai-kō Kōryū-kai - Dantai-sen ①-?)",
    ],
    coverCharacters: ["Satoru Gojo"],
  },
  {
    id: 26,
    name: "Kyoto Sister School Goodwill Event Vol.5",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken5.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol5.jpg",
    imageAlt: "Product 26",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "035. Kyoto Sister School Goodwill Event - Team Battle, Part 2 (京きょう都と姉し妹まい校こう交こう流りゅう会かいー団だん体たい戦せん②ー Kyōto Shimai-kō Kōryū-kai - Dantai-sen ②-?)",
      "036. Kyoto Sister School Goodwill Event - Team Battle, Part 3 (京きょう都と姉し妹まい校こう交こう流りゅう会かいー団だん体たい戦せん③ー Kyōto Shimai-kō Kōryū-kai - Dantai-sen ③-?)",
      "037. Kyoto Sister School Goodwill Event - Team Battle, Part 4 (京きょう都と姉し妹まい校こう交こう流りゅう会かいー団だん体たい戦せん④ー Kyōto Shimai-kō Kōryū-kai - Dantai-sen ④-?)",
      "038. Kyoto Sister School Goodwill Event - Team Battle, Part 5 (京きょう都と姉し妹まい校こう交こう流りゅう会かいー団だん体たい戦せん⑤ー Kyōto Shimai-kō Kōryū-kai - Dantai-sen ⑤-?)",
      "039. Kyoto Sister School Goodwill Event - Team Battle, Part 6 (京きょう都と姉し妹まい校こう交こう流りゅう会かいー団だん体たい戦せん⑥ー Kyōto Shimai-kō Kōryū-kai - Dantai-sen ⑥-?)",
      "040. Kyoto Sister School Goodwill Event - Team Battle, Part 7 (京きょう都と姉し妹まい校こう交こう流りゅう会かいー団だん体たい戦せん⑦ー Kyōto Shimai-kō Kōryū-kai - Dantai-sen ⑦-?)",
      "041. Kyoto Sister School Goodwill Event - Team Battle, Part 8 (京きょう都と姉し妹まい校こう交こう流りゅう会かいー団だん体たい戦せん⑧ー Kyōto Shimai-kō Kōryū-kai - Dantai-sen ⑧-?)",
      "042. Kyoto Sister School Goodwill Event - Team Battle, Part 9 (京きょう都と姉し妹まい校こう交こう流りゅう会かいー団だん体たい戦せん⑨ー Kyōto Shimai-kō Kōryū-kai - Dantai-sen ⑨-?)",
      "043. Kyoto Sister School Goodwill Event - Team Battle, Part 10 (京きょう都と姉し妹まい校こう交こう流りゅう会かいー団だん体たい戦せん⑩ー Kyōto Shimai-kō Kōryū-kai - Dantai-sen ⑩-?)",
    ],
    coverCharcters: ["Aoi Todo", "Nobuko Takada"],
  },
  {
    id: 27,
    name: "Black Flash Vol.6",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken6.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol6.jpg",
    imageAlt: "Product 27",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "044. Kyoto Sister School Goodwill Event - Team Battle, Part 11 (京きょう都と姉し妹まい校こう交こう流りゅう会かいー団だん体たい戦せん⑪ー Kyōto Shimai-kō Kōryū-kai - Dantai-sen ⑪-?)",
      "045. Sage (賢けん者じゃ Kenja?)",
      "046. Time (時じ間かん Jikan?)",
      "047. Cursed Tools (呪じゅ具ぐ Jugu?)",
      "048. Black Flash (黒こく閃せん Kokusen?)",
      "049. Constrained (窮きゅう屈くつ Kyūkutsu?)",
      "050. Feeling (予よ感かん Yokan?)",
      "051. A Flower Offering (供よ花かん Kuge?)",
      "052. Nonstandard (規き格かく外がい Kikaku-gai?)",
    ],
    coverCharacters: ["Mahito"],
  },
  {
    id: 28,
    name: "The Origin of Obedience Vol.7",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken7.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol7.jpg",
    imageAlt: "Product 28",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "053. Completion (完かん遂すい Kansui?)",
      "054. Jujutsu Koshien (呪じゅ術じゅつ甲こう子し園えん Jujutsu Kōshien?)",
      "055. The Origin of Obedience (起き首しゅ雷らい同どう Kishu Raidō?)",
      "056. The Origin of Obedience, Part 2 (起き首しゅ雷らい同どうー弐にー Kishu Raidō -ni-?)",
      "057. The Origin of Obedience, Part 3 (起き首しゅ雷らい同どうー参さんー Kishu Raidō -san-?)",
      "058. The Origin of Obedience, Part 4 (起き首しゅ雷らい同どうー肆しー Kishu Raidō -shi-?)",
      "059. The Origin of Obedience, Part 5 (起き首しゅ雷らい同どうー伍ごー Kishu Raidō -go-?)",
      "060. The Origin of Obedience, Part 6 (起き首しゅ雷らい同どうー陸ろくー Kishu Raidō -roku-?)",
      "061. The Origin of Obedience, Part 7 (起き首しゅ雷らい同どうー漆しちー Kishu Raidō -shichi-?)",
    ],
    coverCharacters: ["Choso", "Eso", "Kechizu"],
  },
  {
    id: 29,
    name: "Hidden Inventory Vol.8",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken8.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol8.jpg",
    imageAlt: "Product 29",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "062. The Origin of Obedience, Part 8 (起き首しゅ雷らい同どうー捌はちー Kishu Raidō -hachi-?)",
      "063. Accomplices (共きょう犯はん Kyōhan?)",
      "064. It's Like That (そういうこと Sō iu Koto?)",
      "065. Hidden Inventory (懐かい玉ぎょく Kaigyoku?)",
      "066. Hidden Inventory, Part 2 (懐かい玉ぎょくー弐にー Kaigyoku -ni-?)",
      "067. Hidden Inventory, Part 3 (懐かい玉ぎょくー参さんー Kaigyoku -san-?)",
      "068. Hidden Inventory, Part 4 (懐かい玉ぎょくー肆しー Kaigyoku -shi-?)",
      "069. Hidden Inventory, Part 5 (懐かい玉ぎょくー伍ごー Kaigyoku -go-?)",
      "070. Hidden Inventory, Part 6 (懐かい玉ぎょくー陸ろくー Kaigyoku -roku-?)",
    ],
    coverCharacters: ["Toji Fushiguro"],
  },
  {
    id: 30,
    name: "Premature Death Vol.9",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken9.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol9.jpg",
    imageAlt: "Product 30",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "071. Hidden Inventory, Part 7 (懐かい玉ぎょくー漆しちー Kaigyoku -shichi-?)",
      "072. Hidden Inventory, Part 8 (懐かい玉ぎょくー捌はちー Kaigyoku -hachi-?)",
      "073. Hidden Inventory, Part 9 (懐かい玉ぎょくー玖くー Kaigyoku -ku-?)",
      "074. Hidden Inventory, Part 10 (懐かい玉ぎょくー拾じゅうー Kaigyoku -jū-?)",
      "075. Hidden Inventory, Part 11 (懐かい玉ぎょくー拾じゅう壱いちー Kaigyoku -jū ichi-?)",
      "076. Premature Death (玉ぎょく折せつ Gyokusetsu?)",
      "077. Premature Death, Part 2 (玉ぎょく折せつー弐にー Gyokusetsu -ni-?)",
      "078. Premature Death, Part 3 (玉ぎょく折せつー参さんー Gyokusetsu -san-?)",
      "079. A Taste of Things to Come (これからの話はなし Korekara no Hanashi?)",
    ],
    coverCharacters: ["Suguru Geto"],
  },
  {
    id: 31,
    name: "Evening Festival Vol.10",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken10.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol10.jpg",
    imageAlt: "Product 31",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "080. Evening Festival (宵よい祭まつり Yoimatsuri?)",
      "081. Evening Festival, Part 2 (宵よい祭まつりー弐にー Yoimatsuri -ni-?)",
      "082. Evening Festival, Part 3 (宵よい祭まつりー参さんー Yoimatsuri -san-?)",
      "083. The Shibuya Incident, Part 1 (渋しぶ谷や事じ変へん① Shibuya Jihen 1?)",
      "084. The Shibuya Incident, Part 2 (渋しぶ谷や事じ変へん② Shibuya Jihen 2?)",
      "085. The Shibuya Incident, Part 3 (渋しぶ谷や事じ変へん③ Shibuya Jihen 3?)",
      "086. The Shibuya Incident, Part 4 (渋しぶ谷や事じ変へん④ Shibuya Jihen 4?)",
      "087. The Shibuya Incident, Part 5 (渋しぶ谷や事じ変へん⑤ Shibuya Jihen 5?)",
      "088. The Shibuya Incident, Part 6 (渋しぶ谷や事じ変へん⑥ Shibuya Jihen 6?)",
    ],
    coverCharacters: ["Kokichi Muta"],
  },
  {
    id: 32,
    name: "The Shibuya Incident Gate Open Vol.11",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken11.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol11.jpg",
    imageAlt: "Product 32",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "089. The Shibuya Incident, Part 7 (渋しぶ谷や事じ変へん⑦ Shibuya Jihen 7?)",
      "090. The Shibuya Incident, Part 8 (渋しぶ谷や事じ変へん⑧ Shibuya Jihen 8?)",
      "091. The Shibuya Incident, Part 9 (渋しぶ谷や事じ変へん⑨ Shibuya Jihen 9?)",
      "092. The Shibuya Incident, Part 10 (渋しぶ谷や事じ変へん⑩ Shibuya Jihen 10?)",
      "093. The Shibuya Incident, Part 11 (渋しぶ谷や事じ変へん⑪ Shibuya Jihen 11?)",
      "094. The Shibuya Incident, Part 12 (渋しぶ谷や事じ変へん⑫ Shibuya Jihen 12?)",
      "095. The Shibuya Incident, Part 13 (渋しぶ谷や事じ変へん⑬ Shibuya Jihen 13?)",
      "096. The Shibuya Incident, Part 14 (渋しぶ谷や事じ変へん⑭ Shibuya Jihen 14?)",
      "097. The Shibuya Incident, Part 15 (渋しぶ谷や事じ変へん⑮ Shibuya Jihen 15?)",
    ],
    coverCharacters: ["Kento Nanami"],
  },
  {
    id: 33,
    name: "The Shibuya Incident Summon Vol.12",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken12.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol12.jpg",
    imageAlt: "Product 33",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "098. The Shibuya Incident, Part 16 (渋しぶ谷や事じ変へん⑯ Shibuya Jihen 16?)",
      "099. The Shibuya Incident, Part 17 (渋しぶ谷や事じ変へん⑰ Shibuya Jihen 17?)",
      "100. The Shibuya Incident, Part 18 (渋しぶ谷や事じ変へん⑱ Shibuya Jihen 18?)",
      "101. The Shibuya Incident, Part 19 (渋しぶ谷や事じ変へん⑲ Shibuya Jihen 19?)",
      "102. The Shibuya Incident, Part 20 (渋しぶ谷や事じ変へん⑳ Shibuya Jihen 20?)",
      "103. The Shibuya Incident, Part 21 (渋しぶ谷や事じ変へん㉑ Shibuya Jihen 21?)",
      "104. The Shibuya Incident, Part 22 (渋しぶ谷や事じ変へん㉒ Shibuya Jihen 22?)",
      "105. The Shibuya Incident, Part 23 (渋しぶ谷や事じ変へん㉓ Shibuya Jihen 23?)",
      "106. The Shibuya Incident, Part 24 (渋しぶ谷や事じ変へん㉔ Shibuya Jihen 24?)",
    ],
    coverCharacters: ["Mei Mei"],
  },
  {
    id: 34,
    name: " The Shibuya Incident Thunderclap Vol.13",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken13.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol13.jpg",
    imageAlt: "Product 34",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "107. The Shibuya Incident, Part 25 (渋しぶ谷や事じ変へん㉕ Shibuya Jihen 25?)",
      "108. The Shibuya Incident, Part 26 (渋しぶ谷や事じ変へん㉖ Shibuya Jihen 26?)",
      "109. The Shibuya Incident, Part 27 (渋しぶ谷や事じ変へん㉗ Shibuya Jihen 27?)",
      "110. The Shibuya Incident, Part 28 (渋しぶ谷や事じ変へん㉘ Shibuya Jihen 28?)",
      "111. The Shibuya Incident, Part 29 (渋しぶ谷や事じ変へん㉙ Shibuya Jihen 29?)",
      "112. The Shibuya Incident, Part 30 (渋しぶ谷や事じ変へん㉚ Shibuya Jihen 30?)",
      "113. The Shibuya Incident, Part 31 (渋しぶ谷や事じ変へん㉛ Shibuya Jihen 31?)",
      "114. The Shibuya Incident, Part 32 (渋しぶ谷や事じ変へん㉜ Shibuya Jihen 32?)",
      "115. The Shibuya Incident, Part 33 (渋しぶ谷や事じ変へん㉝ Shibuya Jihen 33?)",
    ],
    coverCharacters: ["Atsuya Kusakabe"],
  },
  {
    id: 35,
    name: "The Shibuya Incident Right and Wrong Vol.14",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken14.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol14.jpg",
    imageAlt: "Product 35",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "116. The Shibuya Incident, Part 34 (渋しぶ谷や事じ変へん㉞ Shibuya Jihen 34?)",
      "117. The Shibuya Incident, Part 35 (渋しぶ谷や事じ変へん㉟ Shibuya Jihen 35?)",
      "118. The Shibuya Incident, Part 36 (渋しぶ谷や事じ変へん㊱ Shibuya Jihen 36?)",
      "119. The Shibuya Incident, Part 37 (渋しぶ谷や事じ変へん㊲ Shibuya Jihen 37?)",
      "120. The Shibuya Incident, Part 38 (渋しぶ谷や事じ変へん㊳ Shibuya Jihen 38?)",
      "121. The Shibuya Incident, Part 39 (渋しぶ谷や事じ変へん㊴ Shibuya Jihen 39?)",
      "122. The Shibuya Incident, Part 40 (渋しぶ谷や事じ変へん㊵ Shibuya Jihen 40?)",
      "123. The Shibuya Incident, Part 41 (渋しぶ谷や事じ変へん㊶ Shibuya Jihen 41?)",
      "124. The Shibuya Incident, Part 42 (渋しぶ谷や事じ変へん㊷ Shibuya Jihen 42?)",
    ],
    coverCharacters: ["Sukuna"],
  },
  {
    id: 36,
    name: "The Shibuya Incident Transformation Vol.15",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken15.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol15.jpg",
    imageAlt: "Product 36",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "125. A Story About that Girl (あの子この話はなし Ano Ko no Hanashi?)",
      "126. The Shibuya Incident, Part 43 (渋しぶ谷や事じ変へん㊸ Shibuya Jihen 43?)",
      "127. The Shibuya Incident, Part 44 (渋しぶ谷や事じ変へん㊹ Shibuya Jihen 44?)",
      "128. The Shibuya Incident, Part 45 (渋しぶ谷や事じ変へん㊺ Shibuya Jihen 45?)",
      "129. The Shibuya Incident, Part 46 (渋しぶ谷や事じ変へん㊻ Shibuya Jihen 46?)",
      "130. The Shibuya Incident, Part 47 (渋しぶ谷や事じ変へん㊼ Shibuya Jihen 47?)",
      "131. The Shibuya Incident, Part 48 (渋しぶ谷や事じ変へん㊽ Shibuya Jihen 48?)",
      "132. The Shibuya Incident, Part 49 (渋しぶ谷や事じ変へん㊾ Shibuya Jihen 49?)",
      "133. The Shibuya Incident, Part 50 (渋しぶ谷や事じ変へん㊿ Shibuya Jihen 50?)",
    ],
    coverCharacters: ["Mahito"],
  },
  {
    id: 37,
    name: "The Shibuya Incident Gate Closed Vol.16",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken16.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol16.jpg",
    imageAlt: "Product 37",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "134. The Shibuya Incident, Part 51 (渋しぶ谷や事じ変へん51 Shibuya Jihen 51?)",
      "135. The Shibuya Incident, Part 52 (渋しぶ谷や事じ変へん52 Shibuya Jihen 52?)",
      "136. The Shibuya Incident, Part 53 (渋しぶ谷や事じ変へん53 Shibuya Jihen 53?)",
      "137. Hard and White (堅けん白ぱく Kenpaku?)",
      "138. The Zenin Clan (禪ぜん院いん家け Zen'in Ke?)",
      "139. Hunter (狩かり人うど Kariudo?)",
      "140. Execution (執しっ行こう Shikkō?)",
      "141. The Front of The Back (うしろのしょうめん Ushiro no Shōmen?)",
      "142. A Big Brother's Back (お兄にいちゃんの背せ中なか Onīchan no Senaka?)",
    ],
    coverCharacters: ["Kenjaku"],
  },
  {
    id: 38,
    name: "Perfect Preparation Vol.17",
    href: "#",
    pages: "200 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken17.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol17.jpg",
    imageAlt: "Product 38",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "143. One More Time (もう一いち度ど Mōichido?)",
      "144. That Place (あの場ば所しょ Ano Basho?)",
      "145. The Back (裏うら Ura?)",
      "146. About the Culling Game (死し滅めつ回かい遊ゆうについて Shimetsu Kaiyū ni Tsuite?)",
      "147. Even Pandas (パンダだって Panda Datte?)",
      "148. Perfect Preparation (葦あしを啣ふくむ Ashi O Fukumu?)",
      "149. Perfect Preparation, Part 2 (葦あしを啣ふくむー弐にー Ashi O Fukumu -ni-?)",
      "150. Perfect Preparation, Part 3 (葦あしを啣ふくむー参さんー Ashi O Fukumu -san-?)",
      "151. Perfect Preparation, Part 4 (葦あしを啣ふくむー肆しー Ashi O Fukumu -shi-?)",
      "152. Perfect Preparation, Epilogue (葦あしを啣ふくむー跋ばつー Ashi O Fukumu -batsu-?) ",
    ],
    coverCharacters: ["Naoya Zenin"],
  },
  {
    id: 39,
    name: "Fever Vol.18",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken18.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol18.jpg",
    imageAlt: "Product 39",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "153. Underground Fight Club (賭かけ試じ合あい Kake Jiai?)",
      "154. Sneaking In (潜せん入にゅう Sen'nyū?)",
      "155. Fever (熱ねつ Netsu?)",
      "156. Twinkling Stars (きらきら星ほし Kirakira Hoshi?)",
      "157. Cog (部ぶ品ひん Buhin?)",
      "158. Kogane (コガネ Kogane?)",
      "159. Judgement (裁さばき Sabaki?)",
      "160. Colony (結界コロニー Koronī?)",
      "161. Tokyo No. 1 Colony, Part 1 (東とう京きょう第だい１結界コロニー① Tōkyō Dai-Ichi Koronī 1?)",
    ],
    coverCharacters: ["Kinji Hakari"],
  },
  {
    id: 40,
    name: "Tokyo No. 1 Colony Angry Man Vol.19",
    href: "#",
    pages: "EN 200/JP 208 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken19.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol19.jpg",
    imageAlt: "Product 40",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "162. Tokyo No. 1 Colony, Part 2 (東とう京きょう第だい１結界コロニー② Tōkyō Dai-Ichi Koronī 2?)",
      "163. Tokyo No. 1 Colony, Part 3 (東とう京きょう第だい１結界コロニー③ Tōkyō Dai-Ichi Koronī 3?)",
      "164. Tokyo No. 1 Colony, Part 4 (東とう京きょう第だい１結界コロニー④ Tōkyō Dai-Ichi Koronī 4?)",
      "165. Tokyo No. 1 Colony, Part 5 (東とう京きょう第だい１結界コロニー⑤ Tōkyō Dai-Ichi Koronī 5?)",
      "166. Tokyo No. 1 Colony, Part 6 (東とう京きょう第だい１結界コロニー⑥ Tōkyō Dai-Ichi Koronī 6?)",
      "167. Tokyo No. 1 Colony, Part 7 (東とう京きょう第だい１結界コロニー⑦ Tōkyō Dai-Ichi Koronī 7?)",
      "168. Tokyo No. 1 Colony, Part 8 (東とう京きょう第だい１結界コロニー⑧ Tōkyō Dai-Ichi Koronī 8?)",
      "169. Tokyo No. 1 Colony, Part 9 (東とう京きょう第だい１結界コロニー⑨ Tōkyō Dai-Ichi Koronī 9?)",
      "170. Tokyo No. 1 Colony, Part 10 (東とう京きょう第だい１結界コロニー⑩ Tōkyō Dai-Ichi Koronī 10?)",
      "171. Tokyo No. 1 Colony, Part 11 (東とう京きょう第だい１結界コロニー⑪ Tōkyō Dai-Ichi Koronī 11?)",
    ],
    coverCharacters: ["Hiromi Higuruma"],
  },
  {
    id: 41,
    name: "Sendai Colony: The Height of the Feast Vol.20",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken20.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol20.jpg",
    imageAlt: "Product 41",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "172. Tokyo No. 1 Colony, Part 12 (東とう京きょう第だい１結界コロニー⑫ Tōkyō Dai-Ichi Koronī 12?)",
      "173. Tokyo No. 1 Colony, Part 13 (東とう京きょう第だい１結界コロニー⑬ Tōkyō Dai-Ichi Koronī 13?)",
      "174. Sendai Colony, Part 1 (仙台結界せんだいコロニー① Sendai Koronī 1?)",
      "175. Sendai Colony, Part 2 (仙台結界せんだいコロニー② Sendai Koronī 2?)",
      "176. Sendai Colony, Part 3 (仙台結界せんだいコロニー③ Sendai Koronī 3?)",
      "177. Sendai Colony, Part 4 (仙台結界せんだいコロニー④ Sendai Koronī 4?)",
      "178. Sendai Colony, Part 5 (仙台結界せんだいコロニー⑤ Sendai Koronī 5?)",
      "179. Sendai Colony, Part 6 (仙台結界せんだいコロニー⑥ Sendai Koronī 6?)",
      "180. Sendai Colony, Part 7 (仙台結界せんだいコロニー⑦ Sendai Koronī 7?)",
    ],
    coverCharacters: ["Ryu Ishigori"],
  },
  {
    id: 42,
    name: "Tokyo No. 2 Colony Incredible Luck Vol.21",
    href: "#",
    pages: "216 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken21.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol21jpg",
    imageAlt: "Product 42",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chapterList: [
      "181. Tokyo No. 2 Colony, Part 1 (東とう京きょう第だい２結界コロニー① Tōkyō Dai-Ni Koronī 1?)",
      "182. Tokyo No. 2 Colony, Part 2 (東とう京きょう第だい２結界コロニー② Tōkyō Dai-Ni Koronī 2?)",
      "183. Tokyo No. 2 Colony, Part 3 (東とう京きょう第だい２結界コロニー③ Tōkyō Dai-Ni Koronī 3?)",
      "184. Tokyo No. 2 Colony, Part 4 (東とう京きょう第だい２結界コロニー④ Tōkyō Dai-Ni Koronī 4?)",
      "185. Bye-bye (バイバイ Baibai?)",
      "186. Tokyo No. 2 Colony, Part 5 (東とう京きょう第だい２結界コロニー⑤ Tōkyō Dai-Ni Koronī 5?)",
      "187. Tokyo No. 2 Colony, Part 6 (東とう京きょう第だい２結界コロニー⑥ Tōkyō Dai-Ni Koronī 6?)",
      "188. Tokyo No. 2 Colony, Part 7 (東とう京きょう第だい２結界コロニー⑦ Tōkyō Dai-Ni Koronī 7?)",
      "189. Tokyo No. 2 Colony, Part 8 (東とう京きょう第だい２結界コロニー⑧ Tōkyō Dai-Ni Koronī 8?)",
      "190. Tokyo No. 2 Colony, Part 9 (東とう京きょう第だい２結界コロニー⑨ Tōkyō Dai-Ni Koronī 9?)",
    ],
    coverCharacters: ["Hajime Kashimo"],
  },
  {
    id: 43,
    name: "Sakurajima Colony Rebirth Vol.22",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken22.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvo22.jpg",
    imageAlt: "Product 43",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "191. Sakurajima Colony, Part 1 (桜さくら島じま結界コロニー① Sakurajima Koronī 1?)",
      "192. Sakurajima Colony, Part 2 (桜さくら島じま結界コロニー② Sakurajima Koronī 2?)",
      "193. Sakurajima Colony, Part 3 (桜さくら島じま結界コロニー③ Sakurajima Koronī 3?)",
      "194. Sakurajima Colony, Part 4 (桜さくら島じま結界コロニー④ Sakurajima Koronī 4?)",
      "195. Sakurajima Colony, Part 5 (桜さくら島じま結界コロニー⑤ Sakurajima Koronī 5?)",
      "196. Sakurajima Colony, Part 6 (桜さくら島じま結界コロニー⑥ Sakurajima Koronī 6?)",
      "197. Sakurajima Colony, Part 7 (桜さくら島じま結界コロニー⑦ Sakurajima Koronī 7?)",
      "198. Sakurajima Colony, Part 8 (桜さくら島じま結界コロニー⑧ Sakurajima Koronī 8?)",
      "199. Resentful Names (仇あだ名な Adana?)",
    ],
    coverCharacters: ["Maki Zenin", "Mai Zenin"],
  },
  {
    id: 44,
    name: "Stars and Oil Vol.23",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken23.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol23.jpg",
    imageAlt: "Product 44",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "200. Direct Talks, Part 1 (直ちょく接会談せつかいだん① Chokusetsu Kaidan 1?)",
      "201. Direct Talks, Part 2 (直ちょく接会談せつかいだん② Chokusetsu Kaidan 2?)",
      "202. Blood and Oil (血ちと油あぶら Chi to Abura?)",
      "203. Blood and Oil, Part 2 (血ちと油あぶら② Chi to Abura 2?)",
      "204. Blood and Oil, Part 3 (血ちと油あぶら③ Chi to Abura 3?)",
      "205. Stars and Oil (星ほしと油あぶら Hoshi to Abura?)",
      "206. Stars and Oil, Part 2 (星ほしと油あぶら② Hoshi to Abura 2?)",
      "207. Stars and Oil, Part 3 (星ほしと油あぶら③ Hoshi to Abura 3?)",
      "208. Stars and Oil, Part 4 (星ほしと油あぶら④ Hoshi to Abura 4?)",
    ],
    coverCharacters: ["Yuki Tsukumo", "Grauda"],
  },
  {
    id: 45,
    name: "Fearsome Womb Recurrence Vol.24",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken24.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol24.jpg",
    imageAlt: "Product 45",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "209. Offering to the Unknown (未知みちへの供く物もつ Michi e no Kumotsu?)",
      "210. Offering to the Unknown, Part 2 (未知みちへの供く物もつ② Michi e no Kumotsu 2?)",
      "211. The Ripening (熟うむ Umu?)",
      "212. The Ripening, Part 2 (膿うむ② Umu 2?)",
      "213. Fearsome Womb, Part 5 (呪じゅ胎たい戴たい天てんー伍ごー Jutaitaiten -go-?)",
      "214. Fearsome Womb, Part 6 (呪じゅ胎たい戴たい天てんー陸ろくー Jutaitaiten -roku-?)",
      "215. Fearsome Womb, Part 7 (呪じゅ胎たい戴たい天てんー漆しちー Jutaitaiten -shichi-?)",
      "216. Bath (浴よく Yoku?)",
      "217. Bath, Part 2 (浴よく② Yoku 2?)",
    ],
    coverCharacters: ["Hana Kurusu"],
  },
  {
    id: 46,
    name: "Inhuman Makyo Shinjuku Showdown Vol.25",
    href: "#",
    pages: "208 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken25.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol25.jpg",
    imageAlt: "Product 46",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "218. Bath, Part 3 (浴よく③ Yoku 3?)",
      "219. Bath, Part 4 (浴よく④ Yoku 4?)",
      "220. Self-Purification, Self-Constraint (自じ浄じょう自じ縛ばく Jijō Jibaku?)",
      "221. Gain and Loss (得喪とくそう Tokusō?)",
      "222. Foretokens (予よ兆ちょう Yochō?)",
      "223. Inhuman Makyo Shinjuku Showdown, Part 1 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん① Jingai Makyō Shinjuku Kessen 1?)",
      "224. Inhuman Makyo Shinjuku Showdown, Part 2 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん② Jingai Makyō Shinjuku Kessen 2?)",
      "225. Inhuman Makyo Shinjuku Showdown, Part 3 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん③ Jingai Makyō Shinjuku Kessen 3?)",
      "226. Inhuman Makyo Shinjuku Showdown, Part 4 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん④ Jingai Makyō Shinjuku Kessen 4?)",
      "227. Inhuman Makyo Shinjuku Showdown, Part 5 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん⑤ Jingai Makyō Shinjuku Kessen 5?)",
    ],
    coverCharacters: ["Sukuna"],
  },
  {
    id: 47,
    name: "Heading South Vol.26",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken26.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol26.jpg",
    imageAlt: "Product 47",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "228. Inhuman Makyo Shinjuku Showdown, Part 6 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん⑥ Jingai Makyō Shinjuku Kessen 6?)",
      "229. Inhuman Makyo Shinjuku Showdown, Part 7 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん⑦ Jingai Makyō Shinjuku Kessen 7?)",
      "230. Inhuman Makyo Shinjuku Showdown, Part 8 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん⑧ Jingai Makyō Shinjuku Kessen 8?)",
      "231. Inhuman Makyo Shinjuku Showdown, Part 9 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん⑨ Jingai Makyō Shinjuku Kessen 9?)",
      "232. Inhuman Makyo Shinjuku Showdown, Part 10 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん⑩ Jingai Makyō Shinjuku Kessen 10?)",
      "233. Inhuman Makyo Shinjuku Showdown, Part 11 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん⑪ Jingai Makyō Shinjuku Kessen 11?)",
      "234. Inhuman Makyo Shinjuku Showdown, Part 12 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん⑫ Jingai Makyō Shinjuku Kessen 12?)",
      "235. Inhuman Makyo Shinjuku Showdown, Part 13 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん⑬ Jingai Makyō Shinjuku Kessen 13?)",
      "236. Heading South (南みなみへ Minami e?)",
    ],
    coverCharacters: ["Satoru Gojo"],
  },
  {
    id: 48,
    name: "Foolish Survivor!! Vol.27",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken27.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol27.jpg",
    imageAlt: "Product 48",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "237. Inhuman Makyo Shinjuku Showdown, Part 14 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん⑭ Jingai Makyō Shinjuku Kessen 14?)",
      "238. Inhuman Makyo Shinjuku Showdown, Part 15 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん⑮ Jingai Makyō Shinjuku Kessen 15?)",
      "239. Foolish Survivor!! (バカサバイバー！！ Baka Sabaibā!!?)",
      "240. Foolish Survivor —Live On— (バカサバイバー！！〜生いき残のこれ〜 Baka Sabaibā!! ~Ikinokore~?)",
      "241. Foolish Survivor —Win and Remain— (バカサバイバー！！〜勝かち残のこれ〜 Baka Sabaibā!! ~Kachinokore~?)",
      "242. Foolish Survivor —Flying High— (バカサバイバー！！〜舞まい上あがれ〜 Baka Sabaibā!! ~Maiagare~?)",
      "243. Foolish Survivor —Laughing It Up— (バカサバイバー！！〜さんざめけ〜 Baka Sabaibā!! ~Sanzameke~?)",
      "244. Inhuman Makyo Shinjuku Showdown, Part 16 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん⑯ Jingai Makyō Shinjuku Kessen 16?)",
      "245. Inhuman Makyo Shinjuku Showdown, Part 17 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん⑰ Jingai Makyō Shinjuku Kessen 17?)",
    ],
    coverCharacters: ["Fumihiko Takaba"],
  },
  {
    id: 49,
    name: "Inhuman Makyo Shinjuku Showdown Nine Principles Vol.28",
    href: "#",
    pages: "200 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken28.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol28.jpg",
    imageAlt: "Product 49",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "246. Inhuman Makyo Shinjuku Showdown, Part 18 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん⑱ Jingai Makyō Shinjuku Kessen 18?)",
      "247. Inhuman Makyo Shinjuku Showdown, Part 19 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん⑲ Jingai Makyō Shinjuku Kessen 19?)",
      "248. Inhuman Makyo Shinjuku Showdown, Part 20 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん⑳ Jingai Makyō Shinjuku Kessen 20?)",
      "249. Inhuman Makyo Shinjuku Showdown, Part 21 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん㉑ Jingai Makyō Shinjuku Kessen 21?)",
      "250. Inhuman Makyo Shinjuku Showdown, Part 22 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん㉒ Jingai Makyō Shinjuku Kessen 22?)",
      "251. Inhuman Makyo Shinjuku Showdown, Part 23 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん㉓ Jingai Makyō Shinjuku Kessen 23?)",
      "252. Inhuman Makyo Shinjuku Showdown, Part 24 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん㉔ Jingai Makyō Shinjuku Kessen 24?)",
      "253. Inhuman Makyo Shinjuku Showdown, Part 25 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん㉕ Jingai Makyō Shinjuku Kessen 25?)",
      "254. Inhuman Makyo Shinjuku Showdown, Part 26 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん㉖ Jingai Makyō Shinjuku Kessen 26?)",
    ],
    coverCharacters: ["Yuta Okkotsu", "Rika"],
  },
  {
    id: 50,
    name: "Inhuman Makyo Shinjuku Showdown Living Dead Vol.29",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken29.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol29.jpg",
    imageAlt: "Product 50",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "255. Inhuman Makyo Shinjuku Showdown, Part 27 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん㉗ Jingai Makyō Shinjuku Kessen 27?)",
      "256. Inhuman Makyo Shinjuku Showdown, Part 28 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん㉘ Jingai Makyō Shinjuku Kessen 28?)",
      "257. Inhuman Makyo Shinjuku Showdown, Part 29 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん㉙ Jingai Makyō Shinjuku Kessen 29?)",
      "258. Inhuman Makyo Shinjuku Showdown, Part 30 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん㉚ Jingai Makyō Shinjuku Kessen 30?)",
      "259. Inhuman Makyo Shinjuku Showdown, Part 31 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん㉛ Jingai Makyō Shinjuku Kessen 31?)",
      "260. Inhuman Makyo Shinjuku Showdown, Part 32 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん㉜ Jingai Makyō Shinjuku Kessen 32?)",
      "261. Inhuman Makyo Shinjuku Showdown, Part 33 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん㉝ Jingai Makyō Shinjuku Kessen 33?)",
      "262. Inhuman Makyo Shinjuku Showdown, Part 34 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん㉞ Jingai Makyō Shinjuku Kessen 34?)",
      "263. Inhuman Makyo Shinjuku Showdown, Part 35 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん㉟ Jingai Makyō Shinjuku Kessen 35?)",
    ],
    coverCharacters: ["Sukuna"],
  },
  {
    id: 51,
    name: "From Now On Vol.30",
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: "Jujutsu Kaisen/jjken30.jpg",
    imageSrcJapanese: "Jujutsu Kaisen/jjkvol30.jpg",
    imageAlt: "Product 51",
    quantity: 1,
    category: "Jujutsu Kaisen",
    rating: 4.7,
    reviewCount: 149000,
    chaptersList: [
      "264. Inhuman Makyo Shinjuku Showdown, Part 36 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん㊱ Jingai Makyō Shinjuku Kessen 36?)",
      "265. That Day (あの日ひ Ano Hi?)",
      "266. Inhuman Makyo Shinjuku Showdown, Part 37 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん㊲ Jingai Makyō Shinjuku Kessen 37?)",
      "267. Inhuman Makyo Shinjuku Showdown, Part 38 (人外じんがい魔ま境きょう新しん宿じゅく決戦けっせん㊳ Jingai Makyō Shinjuku Kessen 38?)",
      "268. Settling Matters (決けっ着ちゃく Ketchaku?)",
      "269. Considerations (検討けんとう Kentō?)",
      "270. The End of the Dream (夢ゆめの終おわリ Yume no Owari?)",
      "271. From Now On (これから Kore Kara?)",
      "Epilogue (エピローグ Epirōgu?)",
    ],
    coverCharacters: ["Yuji Itadori"],
  },
  ...onePieceTitles.map((title, index) => ({
    id: 52 + index,
    name: `One Piece: ${title} Vol.${index + 1}`,
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: `One Piece/onepiecevol${index + 1}.jpg`,
    imageAlt: `One Piece Vol. ${index + 1}`,
    quantity: 1,
    category: "One Piece",
    rating: 4.7,
    reviewCount: 290000,
  })),

  ...oshiNoKoTitles.map((title, index) => ({
    id: 165 + index,
    name: `Oshi No Ko: ${title} Vol.${index + 1}`,
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: `Oshi No Ko/oshinokojp${index + 1}.jpg`,
    imageSrcJapanese: `Oshi No Ko/oshinoko${index + 1}.jpg`,
    imageAlt: `Oshi No Ko Vol. ${index + 1}`,
    quantity: 1,
    category: "Oshi No Ko",
    rating: 4.4,
    reviewCount: 12000,
    chaptersList: oshiNoKoChapters[index] || [],
    coverCharacters: oshiNoKoCoverCharacters[index] || [],
  })),

  ...demonSlayerTitles.map((title, index) => ({
    id: 200 + index,
    name: `Demon Slayer: ${title} Vol.${index + 1}`,
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: `Demon Slayer/demonen${index + 1}.jpg`,
    imageSrcJapanese: `Demon Slayer/demon${index + 1}.jpg`,
    imageAlt: `Demon Slayer Vol. ${index + 1}`,
    quantity: 1,
    category: "Demon Slayer",
    rating: 4.8,
    reviewCount: 183000,
    chaptersList: demonSlayerChapters[index] || [],
    coverCharacters: demonSlayerCoverCharacters[index] || [],
  })),

  ...jojosBizarreTitles.map((title, index) => ({
    id: 250 + index,
    name: `JoJo's Bizarre Adventure: ${title} Vol.${index + 1}`,
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: `JoJo/jojo${index + 1}.jpg`,
    imageSrcJapanese: `JoJo/jojo${index + 1}.jpg`,
    imageAlt: `JoJo's Bizarre Adventure Vol. ${index + 1}`,
    quantity: 1,
    category: "JoJo's Bizarre Adventure",
    rating: 4.7,
    reviewCount: 42000,
  })),

  ...myDressupDarling.map((title, index) => ({
    id: 350 + index,
    name: `My Dressup Darling: ${title} Vol.${index + 1}`,
    href: "#",
    pages: "192 pages",
    price: "$7.99",
    imageSrcEnglish: `My Dressup Darling/darling${index + 1}.jpg`,
    imageSrcJapanese: `My Dressup Darling/darlingjp${index + 1}.jpg`,
    imageAlt: `My Dressup Darling Vol. ${index + 1}`,
    quantity: 1,
    category: "My Dressup Darling",
    rating: 4.9,
    reviewCount: 160053,
    chaptersList: myDressupDarlingChapters[index] || [],
    coverCharacters: myDressupDarlingCoverCharacters[index] || [],
  })),
];



