import { c } from "node_modules/vite/dist/node/moduleRunnerTransport.d-CXw_Ws6P";

export const Products = [
  {
    id: 1,
    name: "Dog & Chainsaw Vol.1",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrc: "vol1.jpg",
    imageAlt: "Product 1",
    quantity: 1,
  },
  {
    id: 2,
    name: "Chainsaw vs. Bat Vol.2",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrc: "vol2.jpg",
    imageAlt: "Product 2",
    quantity: 1,
  },
  {
    id: 3,
    name: "Kill Denji Vol.3",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrc: "vol3.jpg",
    imageAlt: "Product 3",
    quantity: 1,
  },
  {
    id: 4,
    name: "The Gun is Mightier Vol.4",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrc: "vol4.jpg",
    imageAlt: "Product 4",
    quantity: 1,
  },
  {
    id: 5,
    name: "Minor Vol.5",
    href: "#",
    pages: "200 pages",
    price: "$6.99",
    imageSrc: " vol5.jpg",
    imageAlt: "Product 5",
    quantity: 1,
  },
  {
    id: 6,
    name: "Boom Boom Boom Vol.6",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrc: "vol6.jpg",
    imageAlt: "Product 6",
    quantity: 1,
  },
  {
    id: 7,
    name: "In a Dream Vol.7",
    href: "#",
    pages: "200 pages",
    price: "$6.99",
    imageSrc: "vol7.jpg",
    imageAlt: "Product 7",
    quantity: 1,
  },
  {
    id: 8,
    name: "Super Mess Vol.8",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrc: "vol8.jpg",
    imageAlt: "Product 8",
    quantity: 1,
  },
  {
    id: 9,
    name: "Bath Vol.9",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrc: "vol9.jpg",
    imageAlt: "Product 9",
    quantity: 1,
  },
  {
    id: 10,
    name: "A Dog's Feeling Vol.10",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrc: "1000.png",
    imageAlt: "Product 10",
    quantity: 1,
  },
  {
    id: 11,
    name: "Go Get 'Em, Chainsaw Man Vol.11",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrc: "vol11.jpg",
    imageAlt: "Product 11",
    quantity: 1,
  },
  {
    id: 12,
    name: "Bird and War Vol.12",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrc: "yorujpg.jpg",
    imageAlt: "Product 12",
    quantity: 192,
  },
  {
    id: 13,
    name: "Spoiler Vol.13",
    href: "#",
    pages: "184 pages",
    price: "$6.99",
    imageSrc: "vol13.jpg",
    imageAlt: "Product 13",
    quantity: 1,
  },
  {
    id: 14,
    name: "I Wanna See Penguins! Vol.14",
    href: "#",
    pages: "184 pages",
    price: "$6.99",
    imageSrc: "vol14.jpg",
    imageAlt: "Product 14",
    quantity: 1,
  },
  {
    id: 15,
    name: "Hors D'oeuvre Vol.15",
    href: "#",
    pages: "200 pages",
    price: "$6.99",
    imageSrc: "vol15.jpg",
    imageAlt: "Product 15",
    quantity: 1,
  },
  {
    id: 16,
    name: "Ordinary Happiness Vol.16",
    href: "#",
    pages: "184 pages",
    price: "$6.99",
    imageSrc: "vol16.jpg",
    imageAlt: "Product 16",
    quantity: 1,
  },
  {
    id: 17,
    name: "Guns, Nails, Katana Vol.17",
    href: "#",
    pages: "184 pages",
    price: "$6.99",
    imageSrc: "vol17.jpg",
    imageAlt: "Product 17",
    quantity: 1,
  },
  {
    id: 18,
    name: "All Pets Vol.18",
    href: "#",
    pages: "184 pages",
    price: "$6.99",
    imageSrc: "vol18.jpg",
    imageAlt: "Product 18",
    quantity: 1,
  },
  {
    id: 19,
    name: "Everyday SceneryVol.19",
    href: "#",
    pages: "184 pages",
    price: "$6.99",
    imageSrc: "vol19.jpg",
    imageAlt: "Product 19",
    quantity: 1,
  },
  {
    id: 20,
    name: "Two Children Vol.20",
    href: "#",
    pages: "192 pages",
    price: "$6.99",
    imageSrc: "asa.jpg",
    imageAlt: "Product 20",
    quantity: 1,
  },
];
