export const shonenJumpWikis = [
    "One Piece",
    "Hunter x Hunter",
    "Black Clover",
    "Me & Roboco",
    "Burn the Witch",
    "Sakamoto Days",
    "The Elusive Samurai",
    "Witch Watch",
    "Blue Box",
    "Akane-banshi",
    "RuriDragon",
    "Kill Blue",
    "Nue's Exorcist",
    "Kagurabachi",
    "Super Psychic Policman Chojo",
    "Ultimate Exorcist Kiyoshi",
    "Hima-Ten!",
    "Ichi the Witch",
    "Shinobi Undercover",
    "Syd Craft: Love Is a Mystery",
    "Embers",
  ];

